// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Re-exports the @dnd-kit core + sortable APIs through a single import path
// so captured JSX can reference them without juggling sub-packages.
export {
  DndContext,
  DragOverlay,
  useDraggable,
  useDroppable,
  useSensor,
  useSensors,
  PointerSensor,
  KeyboardSensor,
  closestCenter,
  closestCorners,
} from '@dnd-kit/core';
export type {
  DragEndEvent,
  DragStartEvent,
  DragMoveEvent,
  DragOverEvent,
  Modifier,
} from '@dnd-kit/core';
export {
  SortableContext,
  useSortable,
  arrayMove,
  verticalListSortingStrategy,
  horizontalListSortingStrategy,
  rectSortingStrategy,
} from '@dnd-kit/sortable';
