// Auto-generated by Dr Parity Phase 6 (lib-swap).
//
// Headless UI uses an attribute-rewrite strategy: captured DOM keeps its
// `data-headlessui-state` markers, but the actual Menu / Listbox / Dialog
// component shells need to be wired by hand around the existing markup.
//
// This stub exists so the import path `src/lib/headlessui` is stable. Once
// you wrap a section with @headlessui/react primitives, add the named
// re-exports you need below (e.g. Menu, Listbox, Dialog, Transition).
export {} from '@headlessui/react';
