// Auto-generated by Dr Parity Phase 6 (lib-swap).
// react-beautiful-dnd is unmaintained; this shim re-exports the
// maintained fork @hello-pangea/dnd, which is API-compatible.
export {
  DragDropContext,
  Droppable,
  Draggable,
} from '@hello-pangea/dnd';
export type {
  DragDropContextProps,
  DroppableProps,
  DraggableProps,
  DropResult,
  DragStart,
  DragUpdate,
} from '@hello-pangea/dnd';
