// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Re-exports MultiSelect from react-multi-select-component so captured JSX
// can keep its import path consistent through src/lib/.
export { MultiSelect } from 'react-multi-select-component';
export type { Option } from 'react-multi-select-component';
