// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Default-export wrapper around react-select so captured imports keep working.
import Select from 'react-select';

export default Select;
export { Select };
export type {
  Props as SelectProps,
  GroupBase,
  OptionsOrGroups,
  SingleValue,
  MultiValue,
  ActionMeta,
} from 'react-select';
