// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Re-exports react-slick's default Slider plus the base + theme CSS so
// captured `.slick-*` markup keeps rendering correctly when wrapped in
// <Slider>...</Slider>.
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Slider from 'react-slick';

export default Slider;
export { Slider };
export type { Settings as SliderSettings } from 'react-slick';
