// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Re-exports Swiper React bindings and pulls in the base stylesheet so
// captured `.swiper-container` / `.swiper-slide` markup can be wrapped
// with <Swiper> / <SwiperSlide> without extra CSS plumbing.
import 'swiper/css';

export { Swiper, SwiperSlide } from 'swiper/react';
export type { SwiperProps, SwiperSlideProps } from 'swiper/react';
