// Auto-generated by Dr Parity Phase 6 (lib-swap).
// Re-exports the default Tippy React binding plus the base stylesheet so
// captured `[data-tippy-root]` markup can be wrapped with <Tippy content="..." />.
import 'tippy.js/dist/tippy.css';
import Tippy from '@tippyjs/react';

export default Tippy;
export { Tippy };
export type { TippyProps } from '@tippyjs/react';
