import { mkdir, writeFile, access } from 'fs/promises';
import { join } from 'path';
import type {
  AnimationCall,
  AnimationsSummary,
  EditableModule,
  ExtractResult,
  UneditableEntry,
  AnimationLibrary,
} from './types';

const ALL_LIBRARIES: AnimationLibrary[] = [
  'gsap',
  'scrolltrigger',
  'lenis',
  'intersection-observer',
  'unknown',
];

export async function ensureOutDir(outDir: string, force: boolean): Promise<void> {
  if (force) {
    await mkdir(outDir, { recursive: true });
    return;
  }
  let exists = false;
  try {
    await access(outDir);
    exists = true;
  } catch {
    exists = false;
  }
  if (exists) {
    throw new Error(
      `Output directory already exists: ${outDir}. Pass --force to overwrite.`,
    );
  }
  await mkdir(outDir, { recursive: true });
}

export function buildModules(calls: AnimationCall[]): EditableModule[] {
  const modules: EditableModule[] = [];
  let counter = 0;
  for (const call of calls) {
    if (!call.editable) continue;
    counter += 1;
    const id = String(counter).padStart(3, '0');
    const slug = deriveSlug(call);
    const filename = slug ? `anim-${id}-${slug}.ts` : `anim-${id}.ts`;
    const exportName = `ANIM_${id}`;
    const config = pickEmittableConfig(call);
    modules.push({ id, filename, slug, call, exportName, config });
  }
  return modules;
}

function pickEmittableConfig(call: AnimationCall): Record<string, unknown> | unknown[] {
  if (call.args.length === 0) return {};
  if (call.args.length === 1) {
    const value = call.args[0].value;
    if (isPlainRecord(value) || Array.isArray(value)) {
      return value as Record<string, unknown> | unknown[];
    }
    return { value };
  }
  const merged: Record<string, unknown> = {};
  call.args.forEach((arg, index) => {
    const key = argKeyFor(call.method, index);
    merged[key] = arg.value;
  });
  return merged;
}

function argKeyFor(method: string, index: number): string {
  if (method === 'fromTo') {
    if (index === 0) return 'target';
    if (index === 1) return 'from';
    if (index === 2) return 'to';
  }
  if (method === 'to' || method === 'from' || method === 'set') {
    if (index === 0) return 'target';
    if (index === 1) return 'vars';
  }
  if (method === 'new IntersectionObserver') {
    if (index === 0) return 'callback';
    if (index === 1) return 'options';
  }
  if (index === 0) return 'target';
  return `arg${index}`;
}

function deriveSlug(call: AnimationCall): string {
  const first = call.args[0];
  let raw: string | null = null;
  if (first && first.kind === 'literal' && typeof first.value === 'string') {
    raw = first.value;
  } else if (first && first.kind === 'literal' && isPlainRecord(first.value)) {
    const t = (first.value as Record<string, unknown>).target;
    if (typeof t === 'string') raw = t;
  }
  if (!raw) return '';
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32);
}

export async function writeModules(outDir: string, modules: EditableModule[]): Promise<void> {
  const modulesDir = join(outDir, 'modules');
  await mkdir(modulesDir, { recursive: true });
  for (const m of modules) {
    const body = renderModuleSource(m);
    await writeFile(join(modulesDir, m.filename), body, 'utf8');
  }
  await writeFile(join(modulesDir, 'index.ts'), renderModulesIndex(modules), 'utf8');
}

function renderModuleSource(m: EditableModule): string {
  const header = [
    `// Auto-generated by scripts/extract-animations.ts`,
    `// Source: ${m.call.source.file}:${m.call.source.line}`,
    `// Library: ${m.call.library} | Method: ${m.call.method}`,
    '',
  ].join('\n');
  const body = `export const ${m.exportName} = ${stringifyConfig(m.config)} as const;\n`;
  return header + body;
}

function renderModulesIndex(modules: EditableModule[]): string {
  const lines = [`// Auto-generated index. Do not edit by hand.`, ''];
  for (const m of modules) {
    const base = m.filename.replace(/\.ts$/, '');
    lines.push(`export { ${m.exportName} } from './${base}';`);
  }
  lines.push('');
  return lines.join('\n');
}

function stringifyConfig(value: unknown): string {
  return formatValue(value, 0);
}

function formatValue(value: unknown, indent: number): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  const type = typeof value;
  if (type === 'string') return JSON.stringify(value);
  if (type === 'number' || type === 'boolean') return String(value);
  if (Array.isArray(value)) return formatArray(value, indent);
  if (isPlainRecord(value)) return formatObject(value as Record<string, unknown>, indent);
  return JSON.stringify(value);
}

function formatArray(arr: unknown[], indent: number): string {
  if (arr.length === 0) return '[]';
  const pad = '  '.repeat(indent + 1);
  const close = '  '.repeat(indent);
  const items = arr.map((v) => pad + formatValue(v, indent + 1));
  return `[\n${items.join(',\n')},\n${close}]`;
}

function formatObject(obj: Record<string, unknown>, indent: number): string {
  const keys = Object.keys(obj);
  if (keys.length === 0) return '{}';
  const pad = '  '.repeat(indent + 1);
  const close = '  '.repeat(indent);
  const lines = keys.map((k) => `${pad}${safeKey(k)}: ${formatValue(obj[k], indent + 1)}`);
  return `{\n${lines.join(',\n')},\n${close}}`;
}

function safeKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function isPlainRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

export function buildSummary(
  calls: AnimationCall[],
  uneditable: UneditableEntry[],
  filesScanned: number,
  filesFailed: number,
): AnimationsSummary {
  const byLibrary: AnimationsSummary['byLibrary'] = {
    gsap: { editable: 0, uneditable: 0, total: 0 },
    scrolltrigger: { editable: 0, uneditable: 0, total: 0 },
    lenis: { editable: 0, uneditable: 0, total: 0 },
    'intersection-observer': { editable: 0, uneditable: 0, total: 0 },
    unknown: { editable: 0, uneditable: 0, total: 0 },
  };
  for (const lib of ALL_LIBRARIES) {
    if (!byLibrary[lib]) byLibrary[lib] = { editable: 0, uneditable: 0, total: 0 };
  }
  for (const c of calls) {
    const bucket = byLibrary[c.library];
    bucket.total += 1;
    if (c.editable) bucket.editable += 1;
    else bucket.uneditable += 1;
  }
  return {
    totalCalls: calls.length,
    editable: calls.filter((c) => c.editable).length,
    uneditable: uneditable.length,
    filesScanned,
    filesFailed,
    byLibrary,
  };
}

export async function writeJsonOutputs(
  outDir: string,
  result: ExtractResult,
  plugins: { name: string; file: string; line: number }[],
): Promise<void> {
  await writeFile(
    join(outDir, 'animations-raw.json'),
    JSON.stringify(result.calls, null, 2),
    'utf8',
  );
  await writeFile(
    join(outDir, 'animations-uneditable.json'),
    JSON.stringify(result.uneditable, null, 2),
    'utf8',
  );
  await writeFile(
    join(outDir, 'animations-summary.json'),
    JSON.stringify({ ...result.summary, plugins }, null, 2),
    'utf8',
  );
}
