/**
 * Generate the project-level scaffolding files for the Astro site:
 * package.json, astro.config.mjs, tsconfig.json, README.md.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function writeText(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, 'utf8');
}

export function writePackageJson(outDir: string, name: string): void {
  const pkg = {
    name,
    private: true,
    type: 'module',
    version: '0.0.1',
    scripts: {
      dev: 'astro dev',
      build: 'astro build',
      preview: 'astro preview',
      astro: 'astro',
    },
    dependencies: {
      astro: '^5.0.0',
    },
  };
  writeText(join(outDir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
}

export function writeAstroConfig(outDir: string): void {
  const content =
    "import { defineConfig } from 'astro/config';\n\nexport default defineConfig({ output: 'static' });\n";
  writeText(join(outDir, 'astro.config.mjs'), content);
}

export function writeTsConfig(outDir: string): void {
  const content =
    JSON.stringify({ extends: 'astro/tsconfigs/strict' }, null, 2) + '\n';
  writeText(join(outDir, 'tsconfig.json'), content);
}

export function writeReadme(outDir: string, name: string): void {
  const lines = [
    `# ${name}`,
    '',
    'Astro static project generated by the dr-parity slicer. The captured HTML',
    'has been split into components; styling and assets live under `public/`.',
    '',
    '## Run',
    '',
    '```bash',
    'npm install',
    'npm run dev',
    'npm run build',
    '```',
    '',
    '## Where things live',
    '',
    '- `src/layouts/SiteLayout.astro` controls `<head>`, `<html>` and `<body>` attributes.',
    '- `src/components/Header.astro` and `src/components/Footer.astro` are the chrome.',
    '- `src/components/SectionNN_*.astro` are the page sections in order.',
    '- `src/pages/index.astro` composes the layout and components into the page.',
    '- `public/` holds every asset (CSS, JS, images, fonts). Edit text or markup',
    '  in the component files; edit styles or assets directly in `public/`.',
    '',
    '## Add a new page',
    '',
    '1. Copy `src/pages/index.astro` to `src/pages/<new-route>.astro`.',
    '2. Import the components you need from `../components/`.',
    '3. Wrap them in `<SiteLayout>` with a title and description.',
    '',
  ];
  writeText(join(outDir, 'README.md'), lines.join('\n'));
}

export function writeScaffold(outDir: string, name: string): void {
  writePackageJson(outDir, name);
  writeAstroConfig(outDir);
  writeTsConfig(outDir);
  writeReadme(outDir, name);
}
