/**
 * CSS emitters for tokens.css and overrides.css.
 *
 * tokens.css   — `:root` declaration block with all numeric tokens, grouped by
 *                category, each line annotated with usage + example selector.
 * overrides.css — same tokens but commented-out, ready for per-client overrides.
 */

import {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  type CategorisedTokens,
  type TokenCategory,
  type TokenEntry,
} from './types';

const MAX_COMMENT_LEN = 80;

const TOKENS_HEADER =
  '/* Generated by dr-parity extract-tokens. Do not edit by hand; edit overrides.css instead. */';

const OVERRIDES_HEADER =
  '/* Override tokens here per client. Loaded AFTER tokens.css. */';

export function emitTokensCss(tokens: CategorisedTokens): string {
  const lines: string[] = [TOKENS_HEADER, ':root {'];
  let firstSection = true;

  for (const category of CATEGORY_ORDER) {
    const entries = tokens[category];
    if (entries.length === 0) continue;
    if (!firstSection) lines.push('');
    firstSection = false;
    lines.push(`  /* ${CATEGORY_LABELS[category]} */`);
    for (const entry of entries) {
      lines.push(formatTokenLine(entry, category));
    }
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

export function emitOverridesCss(tokens: CategorisedTokens): string {
  const lines: string[] = [OVERRIDES_HEADER, ':root {'];
  let firstSection = true;

  for (const category of CATEGORY_ORDER) {
    const entries = tokens[category];
    if (entries.length === 0) continue;
    if (!firstSection) lines.push('');
    firstSection = false;
    lines.push(`  /* ${CATEGORY_LABELS[category]} */`);
    for (const entry of entries) {
      lines.push(`  /* --${entry.name}: ${entry.value}; */`);
    }
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

function formatTokenLine(entry: TokenEntry, category: TokenCategory): string {
  const declaration = `  --${entry.name}: ${entry.value};`;
  const comment = buildUsageComment(entry, category);
  if (!comment) return declaration;
  return `${declaration} /* ${comment} */`;
}

function buildUsageComment(entry: TokenEntry, category: TokenCategory): string {
  const parts: string[] = [];
  if (entry.count > 0) {
    parts.push(`used ${entry.count}x`);
  }
  if (entry.exampleSelector) {
    parts.push(`e.g. ${entry.exampleSelector}`);
  } else if (category === 'breakpoints') {
    parts.push('breakpoint');
  }
  if (parts.length === 0) return '';
  const joined = parts.join(' ');
  if (joined.length <= MAX_COMMENT_LEN) return joined;
  return joined.slice(0, MAX_COMMENT_LEN - 1) + '…';
}
