/**
 * TypeScript emitter for tokens.ts.
 *
 * Produces a single `tokens` object literal mapping camelCased token keys to
 * `var(--name)` references, plus a `Token` keyof type.
 */

import { CATEGORY_ORDER, type CategorisedTokens } from './types';

export function emitTokensTs(tokens: CategorisedTokens): string {
  const lines: string[] = [
    '// Generated by dr-parity extract-tokens. Do not edit by hand.',
    '',
    'export const tokens = {',
  ];

  const seen = new Set<string>();
  for (const category of CATEGORY_ORDER) {
    const entries = tokens[category];
    if (entries.length === 0) continue;
    for (const entry of entries) {
      const key = toCamelCase(entry.name);
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`  ${key}: 'var(--${entry.name})',`);
    }
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type Token = keyof typeof tokens;');
  lines.push('');
  return lines.join('\n');
}

function toCamelCase(input: string): string {
  return input.replace(/-([a-z0-9])/gi, (_, ch: string) => ch.toUpperCase());
}
