/**
 * Emits `src/styles/base.css` — resets, body, type roles, table rules,
 * and reduced-motion guard.
 */

export function buildBaseCss(): string {
  return [
    '/* base.css — resets, body, type roles, utilities */',
    '',
    '*,',
    '*::before,',
    '*::after { box-sizing: border-box; }',
    '',
    'html,',
    'body {',
    '  margin: 0;',
    '  padding: 0;',
    '  font-family: var(--sans);',
    '  background: var(--paper);',
    '  color: var(--dark);',
    '  -webkit-font-smoothing: antialiased;',
    '  text-rendering: optimizeLegibility;',
    '}',
    '',
    'img,',
    'svg,',
    'video {',
    '  max-width: 100%;',
    '  display: block;',
    '}',
    '',
    'a {',
    '  color: inherit;',
    '  text-decoration: none;',
    '}',
    '',
    'button {',
    '  font: inherit;',
    '  cursor: pointer;',
    '  background: none;',
    '  border: 0;',
    '  padding: 0;',
    '  color: inherit;',
    '}',
    '',
    '/* Type roles: display headings, body prose, mono for data */',
    'h1, h2, h3, h4, h5, h6 {',
    '  font-family: var(--display);',
    '  margin: 0;',
    '  line-height: 1.15;',
    '}',
    '',
    'p {',
    '  margin: 0;',
    '  line-height: 1.5;',
    '}',
    '',
    '.num,',
    '.mono {',
    '  font-family: var(--mono);',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '',
    '/* Tables: text left, numbers right (apply .num to <td> for numerics) */',
    'table {',
    '  border-collapse: collapse;',
    '  width: 100%;',
    '}',
    '',
    'th,',
    'td {',
    '  text-align: left;',
    '  padding: 8px 12px;',
    '  border-bottom: 1px solid var(--border);',
    '}',
    '',
    'th.num,',
    'td.num {',
    '  text-align: right;',
    '}',
    '',
    '/* Static cards use 1px hairline borders, never drop shadows. */',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  *,',
    '  *::before,',
    '  *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '    scroll-behavior: auto !important;',
    '  }',
    '}',
    '',
  ].join('\n');
}
