/**
 * Emits the project-root files: astro.config.mjs, tsconfig.json, .gitignore,
 * README.md. Pure string templates — no I/O.
 */

import { buildPackageJson } from './package-json-builder';

export interface ScaffoldOptions {
  name: string;
  hasIslands: boolean;
  designName: string;
}

export interface ScaffoldFiles {
  'package.json': string;
  'astro.config.mjs': string;
  'tsconfig.json': string;
  '.gitignore': string;
  'README.md': string;
}

export function buildScaffold(options: ScaffoldOptions): ScaffoldFiles {
  return {
    'package.json': buildPackageJson({ name: options.name, hasIslands: options.hasIslands }),
    'astro.config.mjs': buildAstroConfig(options.hasIslands),
    'tsconfig.json': buildTsconfig(),
    '.gitignore': buildGitignore(),
    'README.md': buildReadme(options.designName),
  };
}

function buildAstroConfig(hasIslands: boolean): string {
  if (hasIslands) {
    return [
      "import { defineConfig } from 'astro/config';",
      "import react from '@astrojs/react';",
      '',
      'export default defineConfig({',
      "  output: 'static',",
      '  integrations: [react()],',
      '});',
      '',
    ].join('\n');
  }
  return [
    "import { defineConfig } from 'astro/config';",
    '',
    'export default defineConfig({',
    "  output: 'static',",
    '});',
    '',
  ].join('\n');
}

function buildTsconfig(): string {
  const cfg = {
    extends: 'astro/tsconfigs/strict',
    include: ['.astro/types.d.ts', '**/*'],
    exclude: ['dist'],
  };
  return JSON.stringify(cfg, null, 2) + '\n';
}

function buildGitignore(): string {
  return [
    '# build output',
    'dist/',
    '.astro/',
    '',
    '# dependencies',
    'node_modules/',
    '',
    '# logs',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'pnpm-debug.log*',
    '',
    '# environment variables',
    '.env',
    '.env.production',
    '',
    '# macOS-specific files',
    '.DS_Store',
    '',
    '# jetbrains setting folder',
    '.idea/',
    '',
  ].join('\n');
}

function buildReadme(designName: string): string {
  return [
    `# ${designName}`,
    '',
    'Generated by **dr-parity** in Astro production mode.',
    '',
    'Static-first Astro 5 project with GSAP-driven motion and minimal React islands',
    'for any interactive widgets. Zero JS is shipped for static sections.',
    '',
    '## Stack',
    '',
    '- Astro 5 (static output)',
    '- GSAP 3 for motion',
    '- React islands via @astrojs/react (only where flagged)',
    '- Vanilla CSS with design tokens as CSS custom properties',
    '',
    '## Commands',
    '',
    '```sh',
    'npm install',
    'npm run dev      # local dev server',
    'npm run build    # static build into dist/',
    'npm run preview  # preview the production build',
    '```',
    '',
    '## File layout',
    '',
    '```',
    'src/',
    '  layouts/BaseLayout.astro      # html shell, fonts, tokens, GSAP init',
    '  styles/tokens.css             # design tokens as :root CSS variables',
    '  styles/base.css               # resets, type roles, utilities',
    '  components/sections/*.astro   # static sections (zero JS)',
    '  components/islands/*.tsx      # React islands (client:visible)',
    '  scripts/animations.ts         # GSAP timelines',
    '  pages/index.astro             # entry page',
    'public/                         # static assets served at site root',
    '```',
    '',
  ].join('\n');
}
