/**
 * Builds chrome.jsx — the shared layout shell.
 *
 * Looks at the topology overlays to decide what to render (sidebar/topbar/footer).
 * Only the overlays actually detected in the extraction are emitted.
 */

import type { TopologyMap, TopologyOverlay } from '../../types/component';

export interface ChromeBuildResult {
  contents: string;
  /** Whether <Chrome> was generated. If false, app.jsx will skip wrapping. */
  hasChrome: boolean;
}

export function buildChromeJsx(topology: TopologyMap): ChromeBuildResult {
  const topbar = topology.overlays.find((o) => o.type === 'header');
  const sidebar = topology.overlays.find((o) => o.type === 'sidebar');
  const footer = topology.overlays.find((o) => o.type === 'footer');

  if (!topbar && !sidebar && !footer) {
    return {
      contents: [
        '/* chrome.jsx — no chrome detected, pass-through */',
        'function Chrome({ children }) { return children; }',
        'Object.assign(window, { Chrome });',
        '',
      ].join('\n'),
      hasChrome: false,
    };
  }

  const lines: string[] = [
    '/* chrome.jsx — shared layout: sidebar/topbar/footer */',
    '',
  ];

  if (topbar) lines.push(renderTopbar(topbar), '');
  if (sidebar) lines.push(renderSidebar(sidebar), '');
  if (footer) lines.push(renderFooter(footer), '');

  lines.push('function Chrome({ children }) {');
  lines.push('  return (');
  lines.push('    <div className="chrome">');
  if (topbar) lines.push('      <Topbar />');
  lines.push('      <div className="chrome-body">');
  if (sidebar) lines.push('        <Sidebar />');
  lines.push('        <main className="chrome-main">{children}</main>');
  lines.push('      </div>');
  if (footer) lines.push('      <Footer />');
  lines.push('    </div>');
  lines.push('  );');
  lines.push('}');
  lines.push('');

  const exports: string[] = ['Chrome'];
  if (topbar) exports.push('Topbar');
  if (sidebar) exports.push('Sidebar');
  if (footer) exports.push('Footer');
  lines.push(`Object.assign(window, { ${exports.join(', ')} });`);
  lines.push('');

  return { contents: lines.join('\n'), hasChrome: true };
}

function renderTopbar(_overlay: TopologyOverlay): string {
  return [
    'function Topbar() {',
    '  return (',
    '    <header className="topbar">',
    '      <div className="topbar-brand">Prototype</div>',
    '    </header>',
    '  );',
    '}',
  ].join('\n');
}

function renderSidebar(_overlay: TopologyOverlay): string {
  return [
    'function Sidebar() {',
    '  return (',
    '    <aside className="sidebar">',
    '      <nav className="sidebar-nav" />',
    '    </aside>',
    '  );',
    '}',
  ].join('\n');
}

function renderFooter(_overlay: TopologyOverlay): string {
  return [
    'function Footer() {',
    '  return (',
    '    <footer className="footer">',
    '      <p className="footer-note">Generated by dr-parity prototype mode</p>',
    '    </footer>',
    '  );',
    '}',
  ].join('\n');
}
