/**
 * media-preserve: safe-mode @media rule extraction.
 *
 * Reads analysis/css-rules.json and emits a responsive.css containing ONLY
 * the captured @media rules, grouped by media query in original cascade
 * order. Then appends the same body into base.css (between idempotent marker
 * comments) so the SiteLayout's existing base.css import picks it up
 * without needing wire-layout changes.
 *
 * Runs in BOTH safe and aggressive modes. Designed so that the aggressive
 * scope-styles emitter (engine/scope-styles/emit.ts) can detect the marker
 * block in base.css and avoid double-emitting the same @media rules.
 *
 * Token substitution is intentionally NOT applied here — that is the
 * aggressive-mode refactor that causes 22-29% pixel diff on enerblock.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { CssRule } from '../analyze/css/types';

export const MEDIA_BLOCK_START = '/* dr-parity:media-preserve:start */';
export const MEDIA_BLOCK_END = '/* dr-parity:media-preserve:end */';

export interface MediaPreserveOptions {
  analysisDir: string;
  stylesOutDir: string;
}

export interface MediaPreserveResult {
  responsiveCssPath: string;
  baseCssPath: string;
  mediaRuleCount: number;
  uniqueMediaQueries: number;
}

export function preserveMediaRules(options: MediaPreserveOptions): MediaPreserveResult {
  const { analysisDir, stylesOutDir } = options;

  const rulesPath = join(analysisDir, 'css-rules.json');
  if (!existsSync(rulesPath)) {
    throw new Error(`media-preserve: missing ${rulesPath}. Run extract:css first.`);
  }

  const rules = readRules(rulesPath);
  const mediaRules = rules.filter((r) => r.mediaQuery !== null && r.mediaQuery !== '');

  const body = serialiseMediaRules(mediaRules);
  const uniqueQueries = new Set(mediaRules.map((r) => r.mediaQuery!)).size;

  mkdirSync(stylesOutDir, { recursive: true });

  const responsiveCssPath = writeResponsiveCss(stylesOutDir, body, mediaRules.length);
  const baseCssPath = upsertBaseCss(stylesOutDir, body);

  return {
    responsiveCssPath,
    baseCssPath,
    mediaRuleCount: mediaRules.length,
    uniqueMediaQueries: uniqueQueries,
  };
}

function readRules(rulesPath: string): CssRule[] {
  const raw = readFileSync(rulesPath, 'utf8');
  const parsed = JSON.parse(raw) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error(`media-preserve: ${rulesPath} is not an array of rules.`);
  }
  return parsed as CssRule[];
}

interface MediaGroup {
  media: string;
  items: CssRule[];
}

/**
 * Stream rules in source order. Start a new group whenever the media
 * context changes so the cascade matches the original capture.
 */
function groupByMedia(rules: CssRule[]): MediaGroup[] {
  const groups: MediaGroup[] = [];
  let current: MediaGroup | null = null;
  for (const r of rules) {
    const media = r.mediaQuery ?? '';
    if (!media) continue;
    if (!current || current.media !== media) {
      current = { media, items: [] };
      groups.push(current);
    }
    current.items.push(r);
  }
  return groups;
}

function serialiseMediaRules(rules: CssRule[]): string {
  const groups = groupByMedia(rules);
  if (groups.length === 0) return '';

  const out: string[] = [];
  for (const { media, items } of groups) {
    out.push(`${media} {`);
    for (const r of items) out.push(serialiseRule(r, 2));
    out.push('}');
  }
  return out.join('\n');
}

function serialiseRule(rule: CssRule, indent: number): string {
  const pad = ' '.repeat(indent);
  const inner = ' '.repeat(indent + 2);
  const body = rule.declarations.map((d) => `${inner}${d.prop}: ${d.value};`).join('\n');
  return `${pad}${rule.selector} {\n${body}\n${pad}}`;
}

function writeResponsiveCss(stylesOutDir: string, body: string, count: number): string {
  const responsivePath = join(stylesOutDir, 'responsive.css');
  const header = `/* Generated by dr-parity media-preserve. ${count} @media rules. */\n`;
  const out = body.length > 0 ? header + body + '\n' : header;
  writeFileSync(responsivePath, out, 'utf8');
  return responsivePath;
}

/**
 * Append (or upsert) the media block into base.css between marker comments.
 * If base.css does not exist yet, create it with just the marker block.
 * Aggressive-mode scope-styles can detect the markers and avoid duplicating.
 */
function upsertBaseCss(stylesOutDir: string, body: string): string {
  const baseCssPath = join(stylesOutDir, 'base.css');
  const block = buildMarkerBlock(body);

  let source = '';
  if (existsSync(baseCssPath)) source = readFileSync(baseCssPath, 'utf8');

  const stripped = stripExistingMediaBlock(source);
  const joined = stripped.length === 0 ? block + '\n' : ensureTrailingNewline(stripped) + block + '\n';

  writeFileSync(baseCssPath, joined, 'utf8');
  return baseCssPath;
}

function buildMarkerBlock(body: string): string {
  if (body.length === 0) {
    return [MEDIA_BLOCK_START, '/* No @media rules captured. */', MEDIA_BLOCK_END].join('\n');
  }
  return [MEDIA_BLOCK_START, body, MEDIA_BLOCK_END].join('\n');
}

export function stripExistingMediaBlock(source: string): string {
  const startIdx = source.indexOf(MEDIA_BLOCK_START);
  const endIdx = source.indexOf(MEDIA_BLOCK_END);
  if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) return source;
  const end = endIdx + MEDIA_BLOCK_END.length;
  const before = source.slice(0, startIdx).replace(/\s+$/, '');
  const after = source.slice(end).replace(/^\s+/, '');
  if (!after) return before.length === 0 ? '' : before + '\n';
  return `${before}\n${after}`;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith('\n') ? s : s + '\n';
}
