/**
 * Authoring source for the runtime post-hydration-sync helper.
 *
 * Both single-page and multi-page React emit pipelines need this exact
 * runtime in every project they generate. To keep the emitted source DRY,
 * each pipeline writes this string to `src/lib/post-hydration-sync.ts` once
 * per project; entry files (`src/main.tsx` for single-page and each
 * `src/entries/<page>.tsx` for multi-page) import `runPostHydrationSync`
 * from there.
 *
 * The behaviour is unchanged from the previous inline version inside
 * `writeMain`. Captured pages depend on third-party libs (GSAP +
 * ScrollTrigger, Greenshift `gspb*`, AOS, etc.) that initialise at
 * `DOMContentLoaded` / `load`. Those events fired against an empty
 * `#root` before React mounted, so we re-fire them, replay each library
 * hook, attach the AOS observer ourselves, and finally strip any stuck
 * `[data-prehidden]` attributes 1500 ms later as a safety net.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

export const POST_HYDRATION_SYNC_SOURCE = [
  '/**',
  ' * Post-hydration sync — runs once per entry, after React commits the',
  ' * initial render. Re-fires DOMContentLoaded/load, replays library hooks',
  ' * (gspb*, AOS, ScrollTrigger), attaches the AOS IntersectionObserver,',
  ' * and as a last-resort safety net strips stuck [data-prehidden]',
  ' * attributes so the page is never permanently blank.',
  ' *',
  ' * Generated by dr-parity. Edit the authoring source at',
  ' * engine/targets/react/post-hydration-sync.ts.',
  ' */',
  '',
  'interface WindowWithLibs {',
  '  gspbBuildAnimation?: () => void;',
  '  gspbInitAnimation?: () => void;',
  '  AOS?: { init?: () => void; refresh?: () => void; refreshHard?: () => void };',
  '  ScrollTrigger?: { refresh?: (safe?: boolean) => void; getAll?: () => unknown[] };',
  '  gsap?: { registerPlugin?: (...args: unknown[]) => void };',
  '}',
  '',
  'function fireLifecycleEvents(): void {',
  '  try { document.dispatchEvent(new Event("DOMContentLoaded", { bubbles: true })); } catch { /* noop */ }',
  '  try { window.dispatchEvent(new Event("load")); } catch { /* noop */ }',
  '}',
  '',
  'function attachAosObservers(): void {',
  "  const els = document.querySelectorAll<HTMLElement>('[data-aos]:not([data-aos-observed])');",
  '  if (els.length === 0) return;',
  '  const io = new IntersectionObserver((entries) => {',
  '    entries.forEach((entry) => {',
  '      const target = entry.target as HTMLElement;',
  "      const once = target.getAttribute('data-aos-once');",
  '      if (entry.isIntersecting) {',
  "        setTimeout(() => { target.classList.add('aos-animate'); }, 10);",
  '        if (once) io.unobserve(target);',
  "      } else if (!once && target.classList.contains('aos-animate') && !target.classList.contains('aos-init')) {",
  "        target.classList.remove('aos-animate');",
  '      }',
  '    });',
  "  }, { threshold: 0, rootMargin: '0px 0px -5% 0px' });",
  '  els.forEach((el) => {',
  "    el.setAttribute('data-aos-observed', '1');",
  '    io.observe(el);',
  '  });',
  '}',
  '',
  'function runLibraryHooks(): void {',
  '  const w = window as unknown as WindowWithLibs;',
  '  try { w.gspbBuildAnimation && w.gspbBuildAnimation(); } catch { /* noop */ }',
  '  try { w.gspbInitAnimation && w.gspbInitAnimation(); } catch { /* noop */ }',
  '  try { w.AOS && w.AOS.init && w.AOS.init(); } catch { /* noop */ }',
  '  try { w.AOS && w.AOS.refreshHard && w.AOS.refreshHard(); } catch { /* noop */ }',
  '  try { w.ScrollTrigger && w.ScrollTrigger.refresh && w.ScrollTrigger.refresh(true); } catch { /* noop */ }',
  '  try { attachAosObservers(); } catch { /* noop */ }',
  '}',
  '',
  'function stripStuckPrehidden(): void {',
  "  document.querySelectorAll('[data-prehidden]').forEach((el) => {",
  "    el.removeAttribute('data-prehidden');",
  '  });',
  '}',
  '',
  'export function runPostHydrationSync(): void {',
  "  if (typeof window === 'undefined') return;",
  '  requestAnimationFrame(() => {',
  '    requestAnimationFrame(() => {',
  '      fireLifecycleEvents();',
  '      runLibraryHooks();',
  '      setTimeout(() => {',
  '        runLibraryHooks();',
  '      }, 100);',
  '      setTimeout(() => {',
  '        runLibraryHooks();',
  '        stripStuckPrehidden();',
  '      }, 1500);',
  '    });',
  '  });',
  '}',
  '',
].join('\n');

/**
 * Write `src/lib/post-hydration-sync.ts` into the given project. Safe to
 * call multiple times — the file is fully overwritten on each call.
 */
export function writePostHydrationSyncLib(srcDir: string): { name: string; bytes: number } {
  const filePath = join(srcDir, 'lib', 'post-hydration-sync.ts');
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, POST_HYDRATION_SYNC_SOURCE, 'utf8');
  return {
    name: 'lib/post-hydration-sync',
    bytes: Buffer.byteLength(POST_HYDRATION_SYNC_SOURCE, 'utf8'),
  };
}
