/**
 * Project-level scaffolding for the generated Vite + React + TS site:
 * package.json, vite.config.ts, tsconfig.json, README.md, globals, and
 * the custom-elements declaration file.
 *
 * Note: the React/Vite versions written here are for the *generated*
 * project's package.json. They do NOT need to be added to dr-parity's
 * own dependencies — dr-parity only writes the manifest, npm at the
 * generated project resolves them at install time. This mirrors how the
 * Astro adapter handles `astro@^5.0.0`.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function writeText(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, 'utf8');
}

function writeTextIfMissing(filePath: string, content: string): boolean {
  if (existsSync(filePath)) return false;
  writeText(filePath, content);
  return true;
}

export function writePackageJson(outDir: string, name: string): void {
  const pkg = {
    name,
    private: true,
    type: 'module',
    version: '0.0.1',
    scripts: {
      dev: 'vite',
      build: 'tsc -b && vite build',
      preview: 'vite preview',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: {
      '@types/react': '^18.3.5',
      '@types/react-dom': '^18.3.0',
      '@vitejs/plugin-react': '^4.3.1',
      typescript: '^5.5.4',
      vite: '^5.4.6',
    },
  };
  writeText(join(outDir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
}

export function writeViteConfig(outDir: string): void {
  const content = [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    '',
    'export default defineConfig({',
    '  plugins: [react()],',
    '});',
    '',
  ].join('\n');
  writeText(join(outDir, 'vite.config.ts'), content);
}

export function writeTsConfig(outDir: string): void {
  const root = {
    compilerOptions: {
      target: 'ES2022',
      useDefineForClassFields: true,
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
      noUnusedLocals: false,
      noUnusedParameters: false,
      noFallthroughCasesInSwitch: true,
    },
    include: ['src'],
  };
  writeText(join(outDir, 'tsconfig.json'), JSON.stringify(root, null, 2) + '\n');
}

export function writeCustomElementsDts(outDir: string): void {
  const filePath = join(outDir, 'src', 'jsx-custom-elements.d.ts');
  const content = [
    '/**',
    ' * Allow any custom element / web component to pass typecheck.',
    ' * Captured sites may include tags like <a-link> or <swiper-slider>.',
    ' */',
    "import 'react';",
    '',
    'declare global {',
    '  namespace JSX {',
    '    interface IntrinsicElements {',
    '      [tag: string]: any;',
    '    }',
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
  writeText(filePath, content);
}

export function writeGlobalCss(outDir: string): void {
  const filePath = join(outDir, 'src', 'styles', 'global.css');
  // Per parity rule: captured CSS lives in /public via <link> tags emitted
  // in the head. This file is a placeholder for any project-specific
  // overrides; it stays empty by default so we don't fight the captured
  // cascade.
  const content = [
    '/* Generated by dr-parity React target.',
    ' *',
    ' * Captured stylesheets are referenced from index.html via <link>',
    ' * tags pointing into /public, preserving the source site cascade',
    ' * verbatim. Add any project-specific overrides below this comment.',
    ' */',
    '',
  ].join('\n');
  writeText(filePath, content);
}

export function writeReadme(outDir: string, name: string): void {
  const lines = [
    `# ${name}`,
    '',
    'React + Vite project generated by the dr-parity slicer. The captured',
    'HTML has been split into TSX components; styling and assets live',
    'under `public/`.',
    '',
    '## Run',
    '',
    '```bash',
    'npm install',
    'npm run dev',
    'npm run build',
    '```',
    '',
    '## Where things live',
    '',
    '- `index.html` controls the page shell, head tags, and `#root`.',
    '- `src/main.tsx` mounts the App into `#root`.',
    '- `src/App.tsx` composes the page from component imports.',
    '- `src/components/*.tsx` are the individual section components.',
    '- `src/components/Main.tsx` wraps the numbered SectionNN components.',
    '- `src/styles/global.css` is a hook for project-level overrides.',
    '- `public/` holds every captured asset (CSS, JS, images, fonts).',
    '',
    '## Custom elements',
    '',
    '`src/jsx-custom-elements.d.ts` widens the JSX type system so any',
    'lowercase custom tag (e.g. `<a-link>`, `<swiper-slider>`) passes',
    'typecheck. Drop typed declarations here once you know the shape.',
    '',
  ];
  writeText(join(outDir, 'README.md'), lines.join('\n'));
}

export function writeEnvExample(outDir: string): void {
  const content = [
    '# Public, build-time env vars only. NO secrets in this file.',
    '# All VITE_* vars are exposed to the browser bundle.',
    '',
    'VITE_SITE_URL=https://example.com',
    '',
    '# Tracking (leave blank to disable each tag)',
    'VITE_GA4_ID=',
    'VITE_GTM_ID=',
    'VITE_META_PIXEL_ID=',
    '',
  ].join('\n');
  writeText(join(outDir, '.env.example'), content);
}

export function writeGitignore(outDir: string): void {
  const content = [
    'node_modules',
    'dist',
    'dist-ssr',
    '*.local',
    '.env',
    '.env.local',
    '.DS_Store',
    '',
  ].join('\n');
  writeTextIfMissing(join(outDir, '.gitignore'), content);
}

export function writeScaffold(outDir: string, name: string): void {
  writePackageJson(outDir, name);
  writeViteConfig(outDir);
  writeTsConfig(outDir);
  writeReadme(outDir, name);
  writeEnvExample(outDir);
  writeGitignore(outDir);
  writeCustomElementsDts(outDir);
  writeGlobalCss(outDir);
}
