/**
 * Multi-page scaffold for the React target.
 *
 * Writes the same baseline files as the single-page scaffold (package.json,
 * tsconfig, README, gitignore, env example, custom-elements types, global
 * CSS placeholder) but emits a multi-entry vite.config.ts that lists each
 * captured page as its own rollup input. This is the key architectural
 * choice — one real HTML entry per page, so navigation does full reloads
 * and every page boots its captured scripts cleanly.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
  writeCustomElementsDts,
  writeEnvExample,
  writeGitignore,
  writeGlobalCss,
  writePackageJson,
  writeTsConfig,
} from './scaffold';

function ensureDir(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function writeText(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, 'utf8');
}

/**
 * Emit vite.config.ts with a multi-entry rollupOptions.input map. Each
 * page name maps to its <outDir>/<pageName>.html file.
 */
export function writeMultiViteConfig(outDir: string, pageNames: readonly string[]): void {
  if (pageNames.length === 0) {
    throw new Error('writeMultiViteConfig: no page names provided');
  }

  // Use bracket-keyed string literals to be safe with arbitrary page slugs.
  const inputEntries = pageNames
    .map((name) => `      ${JSON.stringify(name)}: resolve(__dirname, ${JSON.stringify(`${name}.html`)})`)
    .join(',\n');

  const content = [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    "import { resolve, dirname } from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const __filename = fileURLToPath(import.meta.url);',
    'const __dirname = dirname(__filename);',
    '',
    'export default defineConfig({',
    '  plugins: [react()],',
    '  build: {',
    '    rollupOptions: {',
    '      input: {',
    inputEntries,
    '      },',
    '    },',
    '  },',
    '});',
    '',
  ].join('\n');
  writeText(join(outDir, 'vite.config.ts'), content);
}

export function writeMultiReadme(outDir: string, name: string, pageNames: readonly string[]): void {
  const lines = [
    `# ${name}`,
    '',
    'Multi-page React + Vite project generated by the dr-parity slicer.',
    'Each captured URL becomes a real Vite entry, so navigation between',
    'pages is a full reload (not SPA). This guarantees byte-identical',
    'parity with the source: every page re-runs its captured scripts',
    'and head tags from scratch.',
    '',
    '## Run',
    '',
    '```bash',
    'npm install',
    'npm run dev',
    'npm run build',
    '```',
    '',
    '## Pages',
    '',
    ...pageNames.map((p) => `- \`${p}.html\` -> \`src/entries/${p}.tsx\` -> \`src/pages/${p}Page.tsx\``),
    '',
    '## Where things live',
    '',
    '- `<page>.html` files at the project root are the per-page entries.',
    '- `src/entries/<page>.tsx` mounts the page component and runs the',
    '  post-hydration sync (re-fires DOMContentLoaded/load, replays AOS',
    '  + ScrollTrigger).',
    '- `src/pages/<Page>Page.tsx` composes the page from shared + per-page',
    '  components.',
    '- `src/components/shared/` holds components present on 2+ pages',
    '  (Header, Footer, etc.).',
    '- `src/components/<pageName>/` holds per-page section components.',
    '- `src/lib/post-hydration-sync.ts` is the shared runtime used by',
    '  every entry.',
    '- `src/styles/global.css` is a hook for project-level overrides.',
    '- `public/` holds every captured asset (CSS, JS, images, fonts).',
    '',
    '## Custom elements',
    '',
    '`src/jsx-custom-elements.d.ts` widens the JSX type system so any',
    'lowercase custom tag (e.g. `<a-link>`, `<swiper-slider>`) passes',
    'typecheck. Drop typed declarations here once you know the shape.',
    '',
  ];
  writeText(join(outDir, 'README.md'), lines.join('\n'));
}

/**
 * Public entry: write every scaffold file required for a multi-page
 * React project.
 */
export function writeMultiScaffold(
  outDir: string,
  name: string,
  pageNames: readonly string[],
): void {
  writePackageJson(outDir, name);
  writeMultiViteConfig(outDir, pageNames);
  writeTsConfig(outDir);
  writeMultiReadme(outDir, name, pageNames);
  writeEnvExample(outDir);
  writeGitignore(outDir);
  writeCustomElementsDts(outDir);
  writeGlobalCss(outDir);
}
