/**
 * Emit a human-readable `API_SPEC.md` into the output project root. Consumes
 * the SAME parsed/grouped endpoint data as emit-mocks (via parse-network +
 * group-endpoints), the inferred state groups, and any captured websocket
 * connections, then renders a documentation inventory of the captured app.
 *
 * This is additive and read-only with respect to the crawl: it never mutates
 * the captured logs and produces no runtime code, only documentation.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { loadNetworkRecords } from './emit-mocks/parse-network';
import { groupByEndpoint } from './emit-mocks/group-endpoints';
import type { EndpointGroup, RequestRecord } from './emit-mocks/types';
import { loadWsFrames } from './emit-realtime/load-frames';
import { groupByConnection } from './emit-realtime/group-connections';
import type { ConnectionGroup } from './emit-realtime/types';
import type { RouteGroup } from './inference/types';

const SAMPLE_BODY_MAX = 600;

export interface EmitSpecResult {
  specPath: string;
  bytes: number;
  endpointCount: number;
  wsConnectionCount: number;
}

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  return `${value.slice(0, max)}… (truncated, ${value.length} chars total)`;
}

function prettyBody(raw: string | null | undefined): string {
  if (raw === null || raw === undefined || raw.length === 0) return '(empty)';
  try {
    return JSON.stringify(JSON.parse(raw), null, 2);
  } catch {
    return raw;
  }
}

function codeBlock(language: string, body: string): string {
  return ['```' + language, body, '```'].join('\n');
}

function firstWithRequestBody(records: readonly RequestRecord[]): RequestRecord | undefined {
  return records.find((r) => r.requestBody != null && r.requestBody.length > 0) ?? records[0];
}

function firstWithResponseBody(records: readonly RequestRecord[]): RequestRecord | undefined {
  return records.find((r) => r.responseBody != null && r.responseBody.length > 0) ?? records[0];
}

function statusCodesSeen(records: readonly RequestRecord[]): string {
  const set = new Set<number>();
  for (const r of records) set.add(r.responseStatus);
  return [...set].sort((a, b) => a - b).join(', ');
}

function renderEndpoint(group: EndpointGroup): string {
  const reqRec = firstWithRequestBody(group.records);
  const resRec = firstWithResponseBody(group.records);
  const sampleRequest = truncate(prettyBody(reqRec?.requestBody), SAMPLE_BODY_MAX);
  const sampleResponse = truncate(prettyBody(resRec?.responseBody), SAMPLE_BODY_MAX);

  return [
    `### \`${group.method} ${group.pathPattern}\``,
    '',
    `- Origin: \`${group.origin || '(unknown)'}\``,
    `- Calls captured: ${group.records.length}`,
    `- Status codes seen: ${statusCodesSeen(group.records)}`,
    '',
    'Sample request body:',
    '',
    codeBlock('json', sampleRequest),
    '',
    'Sample response body:',
    '',
    codeBlock('json', sampleResponse),
    '',
  ].join('\n');
}

function renderUiStates(routes: readonly RouteGroup[]): string {
  const rows: string[] = [];
  for (const route of routes) {
    for (const toggle of route.baseStateGroup.toggles) {
      const label = toggle.triggerLabel.length > 0 ? toggle.triggerLabel : '(no label)';
      rows.push(
        `| \`${route.routePath}\` | ${toggle.kind} | \`${toggle.triggerSelector}\` | ${label} | ${toggle.dismissStrategy} |`,
      );
    }
  }

  if (rows.length === 0) {
    return ['## Captured UI states', '', 'No interactive overlay states were captured.', ''].join(
      '\n',
    );
  }

  return [
    '## Captured UI states',
    '',
    '| Route | Kind | Trigger selector | Trigger label | Dismiss |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

function renderWebSockets(connections: readonly ConnectionGroup[]): string {
  if (connections.length === 0) return '';

  const rows = connections.map(
    (c) =>
      `| \`${c.urlPattern}\` | ${c.frames.length} | ${Math.round(c.durationMs)}ms |`,
  );

  return [
    '## WebSocket connections',
    '',
    '| URL pattern | Frames | Duration |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

export async function emitSpec(args: {
  crawlDir: string;
  outDir: string;
  name: string;
  routes: readonly RouteGroup[];
}): Promise<EmitSpecResult> {
  const { crawlDir, outDir, name, routes } = args;

  const { records } = await loadNetworkRecords(crawlDir);
  const groups = records.length > 0 ? groupByEndpoint(records) : [];

  const { frames } = await loadWsFrames(crawlDir);
  const connections = frames.length > 0 ? groupByConnection(frames) : [];

  const sections: string[] = [
    `# API Spec — ${name}`,
    '',
    'Auto-generated by dr-parity (emit-spec) from captured crawl traffic. This is a',
    'documentation inventory of every endpoint, UI state, and websocket connection',
    'observed during the crawl. Re-run the build to regenerate.',
    '',
    `- Endpoints captured: ${groups.length}`,
    `- Total network calls: ${records.length}`,
    `- WebSocket connections: ${connections.length}`,
    '',
    '## Endpoints',
    '',
  ];

  if (groups.length === 0) {
    sections.push('No XHR/fetch traffic was captured during the crawl.', '');
  } else {
    for (const group of groups) sections.push(renderEndpoint(group));
  }

  sections.push(renderUiStates(routes));

  const ws = renderWebSockets(connections);
  if (ws.length > 0) sections.push(ws);

  const content = sections.join('\n');
  const specPath = join(outDir, 'API_SPEC.md');
  writeFileSync(specPath, content, 'utf8');

  return {
    specPath,
    bytes: Buffer.byteLength(content, 'utf8'),
    endpointCount: groups.length,
    wsConnectionCount: connections.length,
  };
}
