/**
 * Emit the replay Service Worker source. Emitted at the ORIGIN ROOT (`/sw.js`)
 * so its default scope is `/` and it controls the whole origin: the page, the
 * app bundle, and every `/_ext/...` asset request. It intercepts EVERY fetch
 * and answers API calls from `recordings.json`.
 *
 * API matching mirrors the emit-mocks handler semantics:
 *   method + templated path (numeric / hex id segments wildcarded) + optional
 *   request-body branch. Unrecorded API requests fall back per `unrecordedMode`:
 *   'empty-200' returns `{}` as 200 JSON (keeps the app alive, avoids login
 *   bounces / hung promises); 'bypass' lets the request hit the real network.
 *
 * Same-origin STATIC requests (the bundle, CSS, fonts, images, media, and the
 * code-split chunks the app lazy-loads) are served from the static file server.
 * When a static request 404s — a lazy chunk / asset the crawl never captured —
 * the SW returns a graceful empty stub with the RIGHT content-type (empty JS
 * module for *.js, empty CSS for *.css, empty body for media) so a missing
 * lazy chunk does not hard-crash the bundle.
 *
 * The SW is plain JS (no bundler) so the emitted project runs under `npx serve`
 * with zero install step.
 */

import type { UnrecordedMode } from './types';

const LOCAL_ASSET_PREFIXES = ['/_ext/', '/_external/', '/media/', '/assets/'];

/**
 * Build the replay Service Worker source.
 *
 * @param unrecordedMode how unmatched API requests are answered (empty-200|bypass).
 * @param backendUrl     ADDITIVE. When a non-empty URL (e.g. http://localhost:8787)
 *                       is passed, the SW first FORWARDS internal-API requests to
 *                       that OWNED local backend; on a backend miss (x-backend:miss)
 *                       or network error it falls back to the existing recordings,
 *                       then empty-200. When empty/null, the SW behaves exactly as
 *                       before (static recordings only) — strict no-regression.
 */
export function buildServiceWorker(unrecordedMode: UnrecordedMode, backendUrl = ''): string {
  return `/**
 * Auto-generated by dr-parity replay target. Intercepts fetch and answers from
 * recorded traffic. Do not edit by hand: re-run build:replay to regenerate.
 */
/* eslint-disable */
'use strict';

const UNRECORDED_MODE = ${JSON.stringify(unrecordedMode)};
const LOCAL_ASSET_PREFIXES = ${JSON.stringify(LOCAL_ASSET_PREFIXES)};
// ADDITIVE proxy mode: when non-empty, internal-API requests are forwarded to
// this OWNED local backend first; backend MISS falls back to recordings.
const BACKEND_URL = ${JSON.stringify(backendUrl)};

let RECORDINGS = [];
// Optional bridge index (task id -> list match key). Absent unless the build
// merged export-generated recordings; when absent, matchKey routing is inert.
let BRIDGE_INDEX = { taskToList: {}, lists: [] };
let recordingsReady = (async () => {
  try {
    const res = await fetch('/replay/recordings.json', { cache: 'no-store' });
    RECORDINGS = await res.json();
  } catch (err) {
    RECORDINGS = [];
  }
  try {
    const res = await fetch('/replay/bridge-index.json', { cache: 'no-store' });
    if (res && res.ok) BRIDGE_INDEX = await res.json();
  } catch (err) {
    /* no bridge index: matchKey routing stays inert */
  }
})();

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

function isLocalAsset(pathname) {
  return LOCAL_ASSET_PREFIXES.some((p) => pathname.startsWith(p));
}

function segmentize(pathname) {
  return pathname.split('/').filter((s) => s.length > 0);
}

/** Mirror emit-mocks id-segment wildcarding: numeric or 8+ hex segments => '*'. */
function normalizedSegments(pathname) {
  return segmentize(pathname).map((s) =>
    /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function patternToSegments(pattern) {
  // emit-mocks emits ':param' placeholders for multi-capture wildcard segments,
  // but a single-capture group keeps the literal id segment. Wildcard both so a
  // request whose id segment we normalized to '*' still matches.
  return segmentize(pattern).map((s) =>
    s.startsWith(':') || /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function pathMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (reqSegs.length !== patSegs.length) return false;
  for (let i = 0; i < patSegs.length; i++) {
    if (patSegs[i] === '*') continue;
    if (patSegs[i] !== reqSegs[i]) return false;
  }
  return true;
}

/**
 * Looser fallback: does the recorded pattern's normalized segment list match a
 * TRAILING slice of the request path? Tolerates a runtime URL that carries one
 * extra LEADING id segment vs the captured pattern (e.g. a regional-shard
 * prefix). Exact match is always tried first in pickRecording; this only runs
 * when nothing matched exactly.
 *
 * IMPORTANT: a head (leading) slice match is deliberately NOT done here. A
 * recorded COLLECTION endpoint (e.g. GET /hierarchy/v1/project — a JSON array
 * of all projects) is a head-slice of a SINGLE-RESOURCE request (e.g. GET
 * /hierarchy/v1/project/901511060743 — one project object, or its /all_statuses
 * sub-resource). Serving the array body for the single-resource request feeds
 * the app a wrong-shaped response and breaks its parser. So we only allow a
 * recorded DEEPER/sibling pattern to answer via a trailing slice, never a
 * shallower collection root.
 */
function pathSubMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (patSegs.length === 0 || patSegs.length > reqSegs.length) return false;
  // Trailing-slice match only. Require at least 2 shared non-wildcard segments
  // so we don't over-match on a single generic segment like 'v1'.
  const offset = reqSegs.length - patSegs.length;
  let concreteTail = 0;
  const tailMatch = patSegs.every((s, i) => {
    if (s === '*') return true;
    concreteTail++;
    return s === reqSegs[offset + i];
  });
  return tailMatch && concreteTail >= 2;
}

function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(stableStringify).join(',') + ']';
  const keys = Object.keys(value).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + stableStringify(value[k])).join(',') + '}';
}

function normalizeBody(raw) {
  if (raw === null || raw === undefined || raw === '') return '';
  try {
    return stableStringify(JSON.parse(raw));
  } catch (err) {
    return raw;
  }
}

/**
 * Compute the bridge match key for a request, used to route per-list bridge
 * recordings that share one wildcarded path pattern to the correct list.
 * Returns '' for any request that is not a bridge endpoint, leaving ordinary
 * matching untouched. Additive: only fires for the three list-view endpoints.
 *   - GET  /hierarchy/v1/subcategory/{listId}   -> 'subcat:{listId}'
 *   - POST /view/v1/genericView                 -> 'gv:{parent.id}'
 *   - POST /task-v3/.../tasks/bulk              -> 'bulk:{list}' via task-id index
 */
function bridgeMatchKey(method, pathname, bodyKey) {
  const subcat = pathname.match(/\\/hierarchy\\/v1\\/subcategory\\/(\\d+)\\b/);
  if (method === 'GET' && subcat) return 'subcat:' + subcat[1];

  if (method === 'POST' && /\\/view\\/v1\\/genericView/.test(pathname)) {
    try {
      const parsed = JSON.parse(bodyKey);
      const id = parsed && parsed.parent && parsed.parent.id;
      if (id) return 'gv:' + String(id);
    } catch (err) {
      /* fall through */
    }
    return '';
  }

  if (method === 'POST' && /\\/task-v3\\/experience\\/\\d+\\/tasks\\/bulk/.test(pathname)) {
    try {
      const parsed = JSON.parse(bodyKey);
      const ids = parsed && parsed.ids;
      if (Array.isArray(ids)) {
        for (let i = 0; i < ids.length; i++) {
          const mk = BRIDGE_INDEX.taskToList[ids[i]];
          if (mk) return mk;
        }
      }
    } catch (err) {
      /* fall through */
    }
    return '';
  }

  return '';
}

function chooseFromCandidates(candidates, bodyKey, wantKey) {
  if (candidates.length === 0) return null;
  // Bridge routing (additive): when the request resolves to a bridge match key
  // and a candidate carries that exact matchKey, it wins outright — this routes
  // a per-list recording sharing a wildcarded path to the right list.
  if (wantKey) {
    const keyed = candidates.find((r) => r.matchKey === wantKey);
    if (keyed) return keyed;
  }
  // Prefer an exact request-body-branch match, then the first body-less record,
  // then any candidate (so GETs without a body still resolve). Among equally
  // valid candidates, prefer one with a non-empty body so a recorded payload
  // beats a recorded empty/304 sibling. Bridge-keyed recordings are skipped here
  // so an unrouted request never grabs an arbitrary list's per-list recording.
  const plain = candidates.filter((r) => !r.matchKey);
  const pool = plain.length > 0 ? plain : candidates;
  const exact = pool.find((r) => r.requestBodyKey === bodyKey);
  if (exact) return exact;
  const empty = pool.find((r) => r.requestBodyKey === '');
  if (empty) return empty;
  const withBody = pool.find((r) => r.body && r.body.length > 2);
  if (withBody) return withBody;
  return pool[0];
}

function pickRecording(method, pathname, bodyKey) {
  const wantKey = bridgeMatchKey(method, pathname, bodyKey);

  // 1. Exact path match (numeric/hex id segments wildcarded). The strict path.
  const exactPath = RECORDINGS.filter(
    (r) => r.method === method && pathMatches(pathname, r.pathPattern),
  );
  const chosen = chooseFromCandidates(exactPath, bodyKey, wantKey);
  if (chosen) return chosen;

  // 2. Tolerant fallback: a recorded sibling endpoint whose normalized segment
  // list is a leading/trailing slice of this request path. Serves a recorded
  // body for a near-miss (sub-resource the crawl did not drill into, or a shard
  // prefix) instead of a bare empty-200. Same method only.
  const subPath = RECORDINGS.filter(
    (r) => r.method === method && pathSubMatches(pathname, r.pathPattern),
  );
  return chooseFromCandidates(subPath, bodyKey, wantKey);
}

// Lightweight served-source counters, readable by a probe via postMessage
// ('replay-stats') or the 'x-replay-source' response header.
let SERVED_RECORDING = 0;
let SERVED_EMPTY200 = 0;
let SERVED_BACKEND = 0;

/**
 * ADDITIVE backend proxy. Forward an internal-API request to the OWNED local
 * backend, preserving method, path, query, and body. Returns the backend
 * Response when it answers LIVE (x-backend:live); returns null on a backend MISS
 * (x-backend:miss) or any network error so the caller falls back to recordings.
 * Inert when BACKEND_URL is empty: behaviour is unchanged (no regression).
 */
async function tryBackend(request, url, method, bodyText) {
  if (!BACKEND_URL) return null;
  let target;
  try {
    const base = new URL(BACKEND_URL);
    target = base.origin + url.pathname + url.search;
  } catch (err) {
    return null;
  }
  const init = {
    method,
    headers: { 'content-type': request.headers.get('content-type') || 'application/json' },
  };
  if (method !== 'GET' && method !== 'HEAD' && bodyText) init.body = bodyText;
  try {
    const res = await fetch(target, init);
    if (!res) return null;
    if (res.headers.get('x-backend') === 'miss') return null;
    const body = await res.text();
    SERVED_BACKEND++;
    return new Response(body, {
      status: res.status,
      headers: {
        'content-type': res.headers.get('content-type') || 'application/json',
        'x-replay-source': 'backend',
        'x-backend': res.headers.get('x-backend') || 'live',
      },
    });
  } catch (err) {
    return null;
  }
}

function recordedResponse(rec) {
  SERVED_RECORDING++;
  return new Response(rec.body, {
    status: rec.status,
    headers: {
      'content-type': rec.contentType || 'application/json',
      'x-replay-source': 'recording',
    },
  });
}

function unrecordedApiResponse(method) {
  if (UNRECORDED_MODE === 'bypass') return null;
  // empty-200: keep the app alive. JSON for fetch/XHR; HEAD/OPTIONS get 204.
  if (method === 'OPTIONS' || method === 'HEAD') {
    return new Response(null, {
      status: 204,
      headers: { 'x-replay-source': 'empty' },
    });
  }
  SERVED_EMPTY200++;
  return new Response('{}', {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'x-replay-source': 'empty',
    },
  });
}

const JS_EXT = /\\.(m?js|cjs)$/i;
const CSS_EXT = /\\.css$/i;
const MEDIA_EXT = /\\.(png|jpe?g|gif|svg|webp|avif|ico|woff2?|ttf|otf|eot|wasm|mp4|webm|m4a|mp3|ogg)$/i;

function looksStatic(pathname) {
  return JS_EXT.test(pathname) || CSS_EXT.test(pathname) || MEDIA_EXT.test(pathname);
}

/**
 * Graceful stub for an uncaptured same-origin static asset (a lazy chunk or
 * asset the crawl never recorded). Returns the RIGHT content-type so a missing
 * file does not hard-crash the bundle: empty JS module for *.js, empty CSS for
 * *.css, empty body otherwise.
 */
function staticStub(pathname) {
  if (JS_EXT.test(pathname)) {
    return new Response('export {};\\n', {
      status: 200,
      headers: { 'content-type': 'application/javascript; charset=utf-8' },
    });
  }
  if (CSS_EXT.test(pathname)) {
    return new Response('/* dr-parity replay: uncaptured stylesheet */\\n', {
      status: 200,
      headers: { 'content-type': 'text/css; charset=utf-8' },
    });
  }
  return new Response(null, { status: 200, headers: { 'content-type': 'application/octet-stream' } });
}

/**
 * Serve a same-origin static request from the static file server; on 404 or a
 * network error, fall back to a typed stub so a missing lazy chunk / asset is
 * non-fatal.
 */
async function handleStatic(request, pathname) {
  try {
    const res = await fetch(request);
    if (res && res.status !== 404) return res;
  } catch (err) {
    /* fall through to stub */
  }
  return staticStub(pathname);
}

async function handleApi(request, url) {
  await recordingsReady;
  const method = request.method.toUpperCase();
  let rawBody = '';
  let bodyKey = '';
  if (method !== 'GET' && method !== 'HEAD') {
    try {
      rawBody = await request.clone().text();
      bodyKey = normalizeBody(rawBody);
    } catch (err) {
      bodyKey = '';
    }
  }

  // 0. ADDITIVE: forward to the OWNED local backend first (live dynamic reads).
  // A backend MISS or error returns null and we fall through to recordings, so
  // without BACKEND_URL set this is inert and behaviour is unchanged.
  const live = await tryBackend(request, url, method, rawBody);
  if (live) return live;

  const rec = pickRecording(method, url.pathname, bodyKey);
  if (rec) return recordedResponse(rec);

  const fallback = unrecordedApiResponse(method);
  if (fallback) return fallback;

  // bypass mode: let it hit the network (will fail offline, by design).
  try {
    return await fetch(request);
  } catch (err) {
    return new Response('{}', {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
}

async function handle(request) {
  const url = new URL(request.url);
  const sameOrigin = url.origin === self.location.origin;

  // Same-origin static asset (localized bundle/CSS/font/image OR a lazy chunk
  // the bundle requests): serve from disk, stubbing 404s so boot survives.
  if (sameOrigin && (isLocalAsset(url.pathname) || looksStatic(url.pathname))) {
    return handleStatic(request, url.pathname);
  }

  return handleApi(request, url);
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Let the browser load the rewritten bootstrap HTML directly.
  if (req.mode === 'navigate') return;
  event.respondWith(handle(req));
});

// Probe hook: a client posts { type: 'replay-stats' } and the SW replies with
// the served-from-recording vs served-empty-200 counts on the message port.
self.addEventListener('message', (event) => {
  if (!event.data || event.data.type !== 'replay-stats') return;
  const stats = { servedRecording: SERVED_RECORDING, servedEmpty200: SERVED_EMPTY200 };
  if (event.ports && event.ports[0]) event.ports[0].postMessage(stats);
});
`;
}
