/**
 * Emit the replay Service Worker source. Emitted at the ORIGIN ROOT (`/sw.js`)
 * so its default scope is `/` and it controls the whole origin: the page, the
 * app bundle, and every `/_ext/...` asset request. It intercepts EVERY fetch
 * and answers API calls from `recordings.json`.
 *
 * API matching mirrors the emit-mocks handler semantics:
 *   method + templated path (numeric / hex id segments wildcarded) + optional
 *   request-body branch. Unrecorded API requests fall back per `unrecordedMode`:
 *   'empty-200' returns `{}` as 200 JSON (keeps the app alive, avoids login
 *   bounces / hung promises); 'bypass' lets the request hit the real network.
 *
 * Same-origin STATIC requests (the bundle, CSS, fonts, images, media, and the
 * code-split chunks the app lazy-loads) are served from the static file server.
 * When a static request 404s — a lazy chunk / asset the crawl never captured —
 * the SW returns a graceful empty stub with the RIGHT content-type (empty JS
 * module for *.js, empty CSS for *.css, empty body for media) so a missing
 * lazy chunk does not hard-crash the bundle.
 *
 * The SW is plain JS (no bundler) so the emitted project runs under `npx serve`
 * with zero install step.
 */

import type { UnrecordedMode } from './types';
import { VIEW_SYNTH_HANDLER_SOURCE } from './synth/view-synth-handler';
import { NORMALIZE_BODY_SOURCE } from './match/normalize-body';
import {
  buildThresholdsSource,
  defaultEndpointPatterns,
  defaultThresholds,
  type EndpointClass,
  type EndpointPattern,
} from './match/endpoint-thresholds';
import { FUZZY_MATCHER_SOURCE } from './match/fuzzy-body-matcher';

export type FuzzyBodyMatchConfig = {
  enabled: boolean;
  thresholds?: Partial<Record<EndpointClass, number>>;
  endpointPatterns?: ReadonlyArray<EndpointPattern>;
};

const LOCAL_ASSET_PREFIXES = ['/_ext/', '/_external/', '/media/', '/assets/', '/replay/'];

/**
 * Build the replay Service Worker source.
 *
 * @param unrecordedMode how unmatched API requests are answered (empty-200|bypass).
 * @param backendUrl     ADDITIVE. When a non-empty URL (e.g. http://localhost:8787)
 *                       is passed, the SW first FORWARDS internal-API requests to
 *                       that OWNED local backend; on a backend miss (x-backend:miss)
 *                       or network error it falls back to the existing recordings,
 *                       then empty-200. When empty/null, the SW behaves exactly as
 *                       before (static recordings only) — strict no-regression.
 * @param originHost     ADDITIVE. The host of the ORIGINAL captured document (e.g.
 *                       app.omnisocials.com). The clone is served from a DIFFERENT
 *                       origin (localhost), so a same-origin asset request the app
 *                       makes by its original ROOT-RELATIVE path (/logos/x.svg,
 *                       /icons/.../facebook.svg) has NO file at that literal path —
 *                       the bytes were localized under /_ext/<originHost>/<path>.
 *                       When the literal same-origin static fetch misses (404 or the
 *                       SPA index.html fallback), the SW retries the /_ext/<originHost>
 *                       copy before stubbing. Empty => the retry is skipped (no
 *                       regression: behaviour is exactly as before).
 */
export function buildServiceWorker(
  unrecordedMode: UnrecordedMode,
  backendUrl = '',
  originHost = '',
  enableViewSynth = false,
  enableDocFreeze = false,
  fuzzyConfig: FuzzyBodyMatchConfig | null = null,
): string {
  const fuzzyEnabled = fuzzyConfig?.enabled === true;
  // Merge profile-supplied patterns/thresholds with defaults. Profile patterns
  // take priority (they appear FIRST so substring match wins them earlier).
  const mergedPatterns: ReadonlyArray<EndpointPattern> = fuzzyEnabled
    ? [...(fuzzyConfig?.endpointPatterns ?? []), ...defaultEndpointPatterns]
    : defaultEndpointPatterns;
  const mergedThresholds = { ...defaultThresholds, ...(fuzzyConfig?.thresholds ?? {}) };
  const fuzzyHelpersSource = fuzzyEnabled
    ? NORMALIZE_BODY_SOURCE +
      buildThresholdsSource(mergedPatterns, mergedThresholds) +
      FUZZY_MATCHER_SOURCE
    : '';
  return `/**
 * Auto-generated by dr-parity replay target. Intercepts fetch and answers from
 * recorded traffic. Do not edit by hand: re-run build:replay to regenerate.
 */
/* eslint-disable */
'use strict';

const UNRECORDED_MODE = ${JSON.stringify(unrecordedMode)};
const LOCAL_ASSET_PREFIXES = ${JSON.stringify(LOCAL_ASSET_PREFIXES)};
// ADDITIVE proxy mode: when non-empty, internal-API requests are forwarded to
// this OWNED local backend first; backend MISS falls back to recordings.
const BACKEND_URL = ${JSON.stringify(backendUrl)};
// ADDITIVE same-origin asset remap: the host of the ORIGINAL captured document.
// A same-origin static request by its original root-relative path (/logos/x.svg)
// has no literal file on the clone origin; the bytes live under /_ext/<host>/...
// On a literal miss the SW retries that localized copy. Empty => retry skipped.
const ORIGIN_HOST = ${JSON.stringify(originHost)};

let RECORDINGS = [];
// Optional bridge index (task id -> list match key). Absent unless the build
// merged export-generated recordings; when absent, matchKey routing is inert.
let BRIDGE_INDEX = { taskToList: {}, lists: [] };
let recordingsReady = (async () => {
  try {
    const res = await fetch('/replay/recordings.json', { cache: 'no-store' });
    RECORDINGS = await res.json();
  } catch (err) {
    RECORDINGS = [];
  }
  try {
    const res = await fetch('/replay/bridge-index.json', { cache: 'no-store' });
    if (res && res.ok) BRIDGE_INDEX = await res.json();
  } catch (err) {
    /* no bridge index: matchKey routing stays inert */
  }
})();

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

function isLocalAsset(pathname) {
  return LOCAL_ASSET_PREFIXES.some((p) => pathname.startsWith(p));
}

function segmentize(pathname) {
  return pathname.split('/').filter((s) => s.length > 0);
}

/** Mirror emit-mocks id-segment wildcarding: numeric or 8+ hex segments => '*'. */
function normalizedSegments(pathname) {
  return segmentize(pathname).map((s) =>
    /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function patternToSegments(pattern) {
  // emit-mocks emits ':param' placeholders for multi-capture wildcard segments,
  // but a single-capture group keeps the literal id segment. Wildcard both so a
  // request whose id segment we normalized to '*' still matches.
  return segmentize(pattern).map((s) =>
    s.startsWith(':') || /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function pathMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (reqSegs.length !== patSegs.length) return false;
  for (let i = 0; i < patSegs.length; i++) {
    if (patSegs[i] === '*') continue;
    if (patSegs[i] !== reqSegs[i]) return false;
  }
  return true;
}

/**
 * How LITERAL a pattern's match against the RAW request path is: the count of
 * pattern segments that equal the corresponding raw request segment verbatim
 * (no wildcarding on either side). When the merged corpus holds several
 * recordings whose ids wildcard to the same path (e.g. a numeric-id 404 sibling
 * viz/v1/view/901523543266 vs the literal viz/v1/view/2kyr6013-1415), the
 * recording that literally names this resource must win so a wrong-list 404
 * never shadows the right-list 200. Same-length match is the precondition.
 */
function literalMatchStrength(requestPath, pattern) {
  const reqRaw = segmentize(requestPath);
  const patRaw = segmentize(pattern);
  let n = 0;
  for (let i = 0; i < patRaw.length && i < reqRaw.length; i++) {
    if (patRaw[i] === reqRaw[i] && !patRaw[i].startsWith(':')) n++;
  }
  return n;
}

/**
 * Looser fallback: does the recorded pattern's normalized segment list match a
 * TRAILING slice of the request path? Tolerates a runtime URL that carries one
 * extra LEADING id segment vs the captured pattern (e.g. a regional-shard
 * prefix). Exact match is always tried first in pickRecording; this only runs
 * when nothing matched exactly.
 *
 * IMPORTANT: a head (leading) slice match is deliberately NOT done here. A
 * recorded COLLECTION endpoint (e.g. GET /hierarchy/v1/project — a JSON array
 * of all projects) is a head-slice of a SINGLE-RESOURCE request (e.g. GET
 * /hierarchy/v1/project/901511060743 — one project object, or its /all_statuses
 * sub-resource). Serving the array body for the single-resource request feeds
 * the app a wrong-shaped response and breaks its parser. So we only allow a
 * recorded DEEPER/sibling pattern to answer via a trailing slice, never a
 * shallower collection root.
 */
function pathSubMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (patSegs.length === 0 || patSegs.length > reqSegs.length) return false;
  // Trailing-slice match only. Require at least 2 shared non-wildcard segments
  // so we don't over-match on a single generic segment like 'v1'.
  const offset = reqSegs.length - patSegs.length;
  let concreteTail = 0;
  const tailMatch = patSegs.every((s, i) => {
    if (s === '*') return true;
    concreteTail++;
    return s === reqSegs[offset + i];
  });
  return tailMatch && concreteTail >= 2;
}

function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(stableStringify).join(',') + ']';
  const keys = Object.keys(value).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + stableStringify(value[k])).join(',') + '}';
}

function normalizeBody(raw) {
  if (raw === null || raw === undefined || raw === '') return '';
  try {
    return stableStringify(JSON.parse(raw));
  } catch (err) {
    return raw;
  }
}

/**
 * Compute the bridge match key for a request, used to route per-list bridge
 * recordings that share one wildcarded path pattern to the correct list.
 * Returns '' for any request that is not a bridge endpoint, leaving ordinary
 * matching untouched. Additive: only fires for the three list-view endpoints.
 *   - GET  /hierarchy/v1/subcategory/{listId}   -> 'subcat:{listId}'
 *   - POST /view/v1/genericView                 -> 'gv:{parent.id}'
 *   - POST /task-v3/.../tasks/bulk              -> 'bulk:{list}' via task-id index
 */
/**
 * Routing key for a genericView request: 'parent.id|view.type', or '' when the
 * request is not a genericView POST or carries no parent id. The view type (1 =
 * list, 5 = calendar, 6 = board, ...) disambiguates a single list whose list AND
 * calendar/board views were both crawled and therefore share one parent id but
 * need DIFFERENT captured payload shapes (list vs calendar block vs board.groups).
 * Routing by parent+type is robust against volatile body fields (cache vectors,
 * timestamps) that defeat an exact body-key match.
 */
function genericViewParentId(method, pathname, bodyKey) {
  if (method !== 'POST' || !/\\/view\\/v1\\/genericView/.test(pathname)) return '';
  try {
    const parsed = JSON.parse(bodyKey);
    const id = parsed && parsed.parent && parsed.parent.id;
    if (!id) return '';
    const type = parsed && parsed.type != null ? String(parsed.type) : '';
    return String(id) + '|' + type;
  } catch (err) {
    return '';
  }
}

function bridgeMatchKey(method, pathname, bodyKey) {
  const subcat = pathname.match(/\\/hierarchy\\/v1\\/subcategory\\/(\\d+)\\b/);
  if (method === 'GET' && subcat) return 'subcat:' + subcat[1];

  if (method === 'POST' && /\\/view\\/v1\\/genericView/.test(pathname)) {
    try {
      const parsed = JSON.parse(bodyKey);
      const id = parsed && parsed.parent && parsed.parent.id;
      if (id) return 'gv:' + String(id);
    } catch (err) {
      /* fall through */
    }
    return '';
  }

  if (method === 'POST' && /\\/task-v3\\/experience\\/\\d+\\/tasks\\/bulk/.test(pathname)) {
    try {
      const parsed = JSON.parse(bodyKey);
      const ids = parsed && parsed.ids;
      if (Array.isArray(ids)) {
        for (let i = 0; i < ids.length; i++) {
          const mk = BRIDGE_INDEX.taskToList[ids[i]];
          if (mk) return mk;
        }
      }
    } catch (err) {
      /* fall through */
    }
    return '';
  }

  return '';
}

function chooseFromCandidates(candidates, bodyKey, wantKey) {
  if (candidates.length === 0) return null;
  // Bridge routing (additive): when the request resolves to a bridge match key
  // and a candidate carries that exact matchKey, it wins outright — this routes
  // a per-list recording sharing a wildcarded path to the right list.
  if (wantKey) {
    const keyed = candidates.find((r) => r.matchKey === wantKey);
    if (keyed) return keyed;
  }
  // Prefer an exact request-body-branch match, then the first body-less record,
  // then any candidate (so GETs without a body still resolve). Among equally
  // valid candidates, prefer one with a non-empty body so a recorded payload
  // beats a recorded empty/304 sibling. Bridge-keyed recordings are skipped here
  // so an unrouted request never grabs an arbitrary list's per-list recording.
  const plain = candidates.filter((r) => !r.matchKey);
  const pool = plain.length > 0 ? plain : candidates;
  const exact = pool.find((r) => r.requestBodyKey === bodyKey);
  if (exact) return exact;
  const empty = pool.find((r) => r.requestBodyKey === '');
  if (empty) return empty;
  // Prefer a 2xx payload over a non-2xx sibling so a wrong-list 404 / 401 never
  // beats a real 200 body when both wildcard-match the same path. Among 2xx,
  // prefer the RICHEST (largest) body: a degenerate status-probe stub (e.g. the
  // 52-byte {"statuses":[],"fields":[]} sibling of a tasks/bulk recording) must
  // never outrank the real multi-KB task payload when no exact body-key match
  // exists. Picking the largest 2xx body is additive — it only changes which
  // bodied sibling wins on a body-key near-miss; exact matches and GETs are
  // unaffected, so nothing that previously worked is stripped.
  const ok = pool.filter((r) => r.status >= 200 && r.status < 300);
  const richest = (list) =>
    list.reduce((best, r) => ((r.body || '').length > (best?.body || '').length ? r : best), null);
  const okWithBody = ok.filter((r) => r.body && r.body.length > 2);
  if (okWithBody.length > 0) return richest(okWithBody);
  if (ok.length > 0) return ok[0];
  const anyWithBody = pool.filter((r) => r.body && r.body.length > 2);
  if (anyWithBody.length > 0) return richest(anyWithBody);
  return pool[0];
}

function pickRecording(method, pathname, bodyKey) {
  const wantKey = bridgeMatchKey(method, pathname, bodyKey);

  // 1. Exact path match (numeric/hex id segments wildcarded). The strict path.
  // When several recordings wildcard-match the same path, restrict to the ones
  // whose literal (non-wildcard) overlap with the RAW request path is greatest,
  // so a recording that literally names this resource (e.g. the right list's
  // view id) beats a numeric-id sibling that only matched via wildcarding (e.g.
  // a wrong-list 404). Ties keep every equally-literal candidate for body/status
  // ranking inside chooseFromCandidates.
  const exactPath = RECORDINGS.filter(
    (r) => r.method === method && pathMatches(pathname, r.pathPattern),
  );
  let strongest = exactPath;
  if (exactPath.length > 1) {
    let best = -1;
    for (const r of exactPath) {
      const s = literalMatchStrength(pathname, r.pathPattern);
      if (s > best) best = s;
    }
    strongest = exactPath.filter((r) => literalMatchStrength(pathname, r.pathPattern) === best);
  }
  const chosen = chooseFromCandidates(strongest, bodyKey, wantKey);
  if (chosen) return chosen;

  // 2. Tolerant fallback: a recorded sibling endpoint whose normalized segment
  // list is a leading/trailing slice of this request path. Serves a recorded
  // body for a near-miss (sub-resource the crawl did not drill into, or a shard
  // prefix) instead of a bare empty-200. Same method only.
  const subPath = RECORDINGS.filter(
    (r) => r.method === method && pathSubMatches(pathname, r.pathPattern),
  );
  return chooseFromCandidates(subPath, bodyKey, wantKey);
}

// Lightweight served-source counters, readable by a probe via postMessage
// ('replay-stats') or the 'x-replay-source' response header.
let SERVED_RECORDING = 0;
let SERVED_EMPTY200 = 0;
let SERVED_BACKEND = 0;

// Per-list TASK-DATA endpoints the OWNED backend serves live. The backend proxy
// is PURELY ADDITIVE and DELIBERATELY NARROW: only the three list-view data
// endpoints are forwarded — exactly the calls whose purpose is to render a
// list's tasks (including lists the crawl never captured). Every init/shell
// endpoint (bootstrap, user, project, customFields, hierarchy, workspace, flags,
// auth, telemetry, CDN) skips the backend and falls through to the captured
// recording, which is richer and correct. This is the no-regression guard: the
// proxy can ONLY add live task data, never shadow an init recording the bundle
// needs to boot and route.
const BACKEND_DATA_PATTERNS = [
  // List-render reads (proven live + store-backed, so writes reflect).
  /\\/hierarchy\\/v1\\/subcategory\\/\\d+/,
  /\\/view\\/v1\\/genericView/,
  /\\/task-v3\\/experience\\/\\d+\\/tasks\\/bulk/,
  // Per-view METADATA read. The backend synthesizes viz/v1/view/{viewId} from a
  // per-type template + the view catalog. GATED end-to-end: the backend returns
  // x-backend:miss (empty {}) for any view it cannot synthesize (uncatalogued or
  // no template for its type), and tryBackend rejects a {} / non-live answer, so
  // the request falls back to the recording / empty-200 exactly as before.
  // Requires a trailing id segment to match.
  /\\/viz\\/v1\\/view\\/[^/]+$/,
  // VIEW-COLLECTION reads (close the view-ROUTE-RESOLUTION gap). The SPA resolves a
  // /v/{type}/{viewId} route by ENUMERATING a location's views via these two
  // collection reads, then binds the target view from the returned views[]:
  //   GET /viz/v1/default_views?parent_id={loc}&parent_type={t}
  //   GET /viz/v1/view?parent_id={loc}&parent_type={t}&...   (bare collection, no id)
  // Recordings answer both for ONE wrong location with views:[] so the target view
  // is never found and the route falls to the default list scaffold. The backend
  // populates views[] from the catalog so the SPA finds + binds the view. GATED in
  // the handler: a parent the catalog does not cover returns x-backend:miss, so the
  // bare-collection recording still answers for uncovered locations (no regression).
  // Anchored to the bare path (no id) so the per-view viz/v1/view/{id} read above is
  // unaffected.
  /\\/viz\\/v1\\/view$/,
  /\\/viz\\/v1\\/default_views$/,
  // Doc render chain (deep-link doc body). The backend serves doc METADATA from the
  // owned export when it owns the requested doc id, else returns x-backend:miss so the
  // recording / empty-200 answers. docs/bulk is GATED in the handler so the hub
  // full-list recording is never shadowed (the handler returns miss unless an owned
  // id is requested). single-doc plus lastViewed complete the metadata chain.
  //
  // The PAGE chain (the page list plus the singular page/id) is DELIBERATELY left to
  // the recordings, NOT the backend. The real page list returns content null with an
  // editor token plus the 45-field page shape the ProseMirror editor mounts from, and
  // the singular page/id carries the Quill Delta content. The backend synth only had a
  // thin markdown shape with no editor token, which mounted the editor shell but never
  // painted the body. Crawling 2 doc deep-links recorded the real page chain, so the
  // recording now serves the correct list plus content and the body paints. Unowned
  // docs have no recording and never painted a body before, so this stays no-regression.
  /\\/docs\\/v1\\/team\\/\\d+\\/docs\\/bulk$/,
  /\\/docs\\/v1\\/team\\/\\d+\\/docs\\/[^/]+$/,
  /\\/docs\\/v1\\/page\\/[^/]+\\/lastViewed$/,
  // NOTE: init/shell reads (bootstrap, workspace-core, user, project, customFields)
  // are deliberately NOT served live. Their store payloads were non-empty but
  // subtly off-shape — they passed the non-degenerate gate yet stalled the bundle's
  // route mount (list never painted). They fall back to the captured recording so
  // the SPA boots+routes exactly as recordings-only mode. Re-widen one at a time
  // ONLY when a payload is parity-verified to keep the list painting.
  // Mutating task routes the bundle/harness POST/PUT/DELETE to; the backend maps
  // these to commands. Non-command writes (telemetry/auth) never match here.
  /\\/cmd\\/v1\\//,
  /\\/v1\\/list\\/\\d+\\/task$/,
  /\\/v1\\/task\\/[0-9a-z]+(\\/(assignee|list|comment))?$/i,
];

// ADDITIVE Tempo seam: when the OWNED backend is a Tempo backend, ALL of its
// /api/v1/... surface is live + DB-backed (reads, canvas CRUD, generation), so
// the proxy forwards the WHOLE /api/v1 namespace rather than the narrow ClickUp-
// era path list above. Two exclusions keep this safe:
//   - PUBLISH / APPROVE writes are NEVER forwarded (sandbox-only on the backend,
//     and we must never fire them from the replay). They fall to recordings.
//   - This widening only applies when BACKEND_URL is set; offline replay (empty
//     BACKEND_URL) never reaches tryBackend, so the canvas mock + recordings
//     still answer exactly as before (strict no-regression).
const BACKEND_FORWARD_NEVER = [
  /\\/prepare-for-publish/,
  /\\/publish-creative/,
  /\\/approvals\\/candidate\\//,
];

function isBackendForwardable(pathname) {
  if (BACKEND_FORWARD_NEVER.some((re) => re.test(pathname))) return false;
  // Tempo seam: forward the whole live /api/v1 surface (reads + canvas CRUD +
  // generation) so writes persist to the DB. Falls back to recordings on miss.
  if (/^\\/api\\/v1\\//.test(pathname)) return true;
  // Legacy ClickUp-era narrow allow-list (unchanged for non-Tempo backends).
  return BACKEND_DATA_PATTERNS.some((re) => re.test(pathname));
}

/**
 * ADDITIVE backend proxy. Forwards a request to the OWNED local backend ONLY
 * when its path matches a routed internal-DATA endpoint (isBackendDataPath).
 * Returns the backend Response when it answers LIVE (x-backend:live); returns
 * null for non-data paths, a backend MISS (x-backend:miss or any non-live
 * answer), an empty body, or any network error — so the caller falls back to
 * the captured recording. Inert when BACKEND_URL is empty (no regression).
 */
async function tryBackend(request, url, method, bodyText) {
  if (!BACKEND_URL) return null;
  // Guard: only forward routed internal-data endpoints (Tempo: the whole live
  // /api/v1 surface minus publish/approve; legacy: the narrow ClickUp list).
  // Everything else (flags, auth, telemetry, CDN) is left for the recording —
  // the proxy never shadows it.
  if (!isBackendForwardable(url.pathname)) return null;
  let target;
  try {
    const base = new URL(BACKEND_URL);
    target = base.origin + url.pathname + url.search;
  } catch (err) {
    return null;
  }
  const init = {
    method,
    headers: { 'content-type': request.headers.get('content-type') || 'application/json' },
  };
  if (method !== 'GET' && method !== 'HEAD' && bodyText) init.body = bodyText;
  try {
    const res = await fetch(target, init);
    if (!res) return null;
    // Only a positive x-backend:live answer wins. miss / absent / anything else
    // falls back to the recording (defensive against a cross-origin header that
    // does not read back as exactly 'live').
    if (res.headers.get('x-backend') !== 'live') return null;
    const body = await res.text();
    // An empty/degenerate body is not real data; let the recording answer.
    if (!body || body === '{}' || body === '[]') return null;
    SERVED_BACKEND++;
    return new Response(nullBodyStatus(res.status) ? null : body, {
      status: res.status,
      headers: {
        'content-type': res.headers.get('content-type') || 'application/json',
        'x-replay-source': 'backend',
        'x-backend': 'live',
      },
    });
  } catch (err) {
    return null;
  }
}

// HTTP statuses whose Response MUST have a null body. The Response constructor
// throws "Response with null body status cannot have body" if a non-null body
// is supplied for any of these, so force the body to null for them.
const NULL_BODY_STATUSES = [101, 204, 205, 304];

function nullBodyStatus(status) {
  return NULL_BODY_STATUSES.indexOf(status) !== -1;
}

function recordedResponse(rec) {
  SERVED_RECORDING++;
  const body = nullBodyStatus(rec.status) ? null : (rec.body != null ? rec.body : null);
  return new Response(body, {
    status: rec.status,
    headers: {
      'content-type': rec.contentType || 'application/json',
      'x-replay-source': 'recording',
    },
  });
}

function unrecordedApiResponse(method) {
  if (UNRECORDED_MODE === 'bypass') return null;
  // empty-200: keep the app alive. JSON for fetch/XHR; HEAD/OPTIONS get 204.
  if (method === 'OPTIONS' || method === 'HEAD') {
    return new Response(null, {
      status: 204,
      headers: { 'x-replay-source': 'empty' },
    });
  }
  SERVED_EMPTY200++;
  return new Response('{}', {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'x-replay-source': 'empty',
    },
  });
}

const JS_EXT = /\\.(m?js|cjs)$/i;
const CSS_EXT = /\\.css$/i;
const MEDIA_EXT = /\\.(png|jpe?g|gif|svg|webp|avif|ico|woff2?|ttf|otf|eot|wasm|mp4|webm|m4a|mp3|ogg)$/i;

function looksStatic(pathname) {
  return JS_EXT.test(pathname) || CSS_EXT.test(pathname) || MEDIA_EXT.test(pathname);
}

/**
 * True when the request is for an image, regardless of URL extension. The browser
 * sends 'Accept: image/avif,image/webp,...,image/*' for an <img> element, so an
 * extensionless avatar URL (Google profile pic .../a/<id>=s96-c) is still routed
 * to the cross-origin static handler and resolves its localized _ext copy. Pure
 * widening of the cross-origin static branch: a non-image request never matches.
 */
function acceptsImage(request) {
  const accept = (request.headers.get('accept') || '').toLowerCase();
  return accept.indexOf('image/') !== -1;
}

/**
 * Graceful stub for an uncaptured same-origin static asset (a lazy chunk or
 * asset the crawl never recorded). Returns the RIGHT content-type so a missing
 * file does not hard-crash the bundle: empty JS module for *.js, empty CSS for
 * *.css, empty body otherwise.
 */
function staticStub(pathname) {
  if (JS_EXT.test(pathname)) {
    return new Response('export {};\\n', {
      status: 200,
      headers: { 'content-type': 'application/javascript; charset=utf-8' },
    });
  }
  if (CSS_EXT.test(pathname)) {
    return new Response('/* dr-parity replay: uncaptured stylesheet */\\n', {
      status: 200,
      headers: { 'content-type': 'text/css; charset=utf-8' },
    });
  }
  return new Response(null, { status: 200, headers: { 'content-type': 'application/octet-stream' } });
}

/**
 * Map a same-origin ROOT-RELATIVE asset path to its localized /_ext/<ORIGIN_HOST>
 * copy. The clone is served from a different origin than the captured app, so the
 * app's original same-origin asset URLs (/logos/x.svg, /icons/.../facebook.svg)
 * have no literal file on the clone origin; the build wrote the bytes under
 * /_ext/<ORIGIN_HOST>/<sanitized-path>, mirroring emit-assets-from-crawl.urlToExtPath
 * for the document host. Returns null when ORIGIN_HOST is unset (retry disabled) or
 * the path is already an _ext path (no double-prefix). Query is dropped: localized
 * first-party assets are written queryless.
 */
function sameOriginToExtPath(pathname) {
  if (!ORIGIN_HOST) return null;
  if (pathname.indexOf('/_ext/') === 0) return null;
  const host = sanitizeSegment(ORIGIN_HOST);
  let rel = pathname
    .split('/')
    .map((seg) => (seg === '' ? '' : sanitizeSegment(seg)))
    .join('/')
    .replace(/^\\/+/, '');
  if (!rel || rel.endsWith('/')) rel = rel + 'index';
  return '/_ext/' + host + '/' + rel;
}

/**
 * True when a static-file fetch did not actually return the asset: a 404, or the
 * SPA index.html fallback (an HTML body for a request whose extension is not
 * .html). Under a SPA static server a missing same-origin asset path resolves to
 * index.html with a 200 + text/html content-type, which the browser rejects for an
 * img/script (the "Unexpected token <" symptom), so HTML for a non-HTML asset is a MISS.
 */
function isStaticMiss(res, pathname) {
  if (!res) return true;
  if (res.status === 404) return true;
  const ct = (res.headers.get('content-type') || '').toLowerCase();
  if (ct.indexOf('text/html') !== -1 && !/\\.html?$/i.test(pathname)) return true;
  return false;
}

/**
 * Serve a same-origin static request from the static file server. On a literal
 * miss (404 or the SPA index.html fallback), retry the localized /_ext/<ORIGIN_HOST>
 * copy of the same path — this resolves the app's original root-relative asset URLs
 * (logo / platform icons / avatars) to the bytes the build localized. On a final
 * miss, fall back to a typed stub so a missing lazy chunk / asset is non-fatal.
 */
async function handleStatic(request, pathname) {
  let res = null;
  try {
    res = await fetch(request);
  } catch (err) {
    /* network error -> try _ext remap, then stub */
  }
  if (res && !isStaticMiss(res, pathname)) return res;

  const extPath = sameOriginToExtPath(pathname);
  if (extPath) {
    try {
      const local = await fetch(extPath, { cache: 'no-store' });
      // Guard against the SPA HTML fallback for an extensionless _ext path (see
      // handleCrossOriginStatic). Extensioned assets (logo/icons/.png) pass.
      if (local && local.ok && !isStaticMiss(local, extPath)) {
        return new Response(local.body, {
          status: 200,
          headers: {
            'content-type': local.headers.get('content-type') || 'application/octet-stream',
            'x-replay-source': 'ext-asset-sameorigin',
          },
        });
      }
    } catch (err) {
      /* fall through to stub */
    }
  }
  return staticStub(pathname);
}

/** Mirror emit-assets-from-crawl's sanitizeSegment so the SW maps a cross-origin
 * asset URL to the SAME local _ext path the build wrote it to. */
function sanitizeSegment(segment) {
  return segment.replace(/[^a-zA-Z0-9._\\-+~@]/g, '_');
}

/**
 * Hosts whose query string is a per-request expiring SIGNATURE (Azure Blob SAS),
 * not a content selector. The same blob is served under infinitely many signed
 * URLs, so the build localizes it queryless and the SW must look it up queryless
 * too — otherwise every canvas ad image 403s once its captured SAS expires.
 */
const SAS_QUERY_HOSTS = new Set(['draperfiles.blob.core.windows.net']);

/**
 * Map a cross-origin asset URL to its localized /_ext/<host>/<path> served path,
 * mirroring emit-assets-from-crawl.urlToExtPath. Query strings are disambiguated
 * by the build with a sha-suffix; the SW only maps the QUERYLESS form (which
 * covers the captured media — ad/project images carry no query). A queried asset
 * returns null and falls through to the live network, so nothing regresses.
 *
 * Exception: SAS-signed hosts (see SAS_QUERY_HOSTS) carry an expiring signature
 * in the query that does NOT identify the blob. For those we STRIP the query and
 * map the queryless path, so a captured image matches regardless of its token.
 */
function urlToExtServedPath(url) {
  if (url.search && !SAS_QUERY_HOSTS.has(url.host)) return null;
  const host = sanitizeSegment(url.host);
  let pathname = url.pathname
    .split('/')
    .map((seg) => (seg === '' ? '' : sanitizeSegment(seg)))
    .join('/')
    .replace(/^\\/+/, '');
  if (!pathname || pathname.endsWith('/')) pathname = pathname + 'index';
  return '/_ext/' + host + '/' + pathname;
}

/**
 * Serve a CROSS-ORIGIN static asset (image/font/media on a captured CDN host,
 * e.g. the ad/project creatives on a blob/CDN origin) from the localized _ext
 * copy. On a local miss (asset the crawl never captured) or a non-static path,
 * fall through to the live network so uncaptured assets still load online —
 * strictly additive, no same-origin or API behaviour changes.
 */
async function handleCrossOriginStatic(request, url) {
  const servedPath = urlToExtServedPath(url);
  if (servedPath) {
    try {
      const local = await fetch(servedPath, { cache: 'no-store' });
      // A 200 whose body is the SPA index.html is NOT the asset: a SPA static
      // server (serve -s) returns index.html for an EXTENSIONLESS localized path
      // (e.g. an avatar at /_ext/lh3.../a/<id>_s96-c). Treat that as a miss so the
      // request falls through to the live network instead of painting HTML into
      // an <img>. Extensioned _ext assets (the logo, icons, .png avatars) are
      // served verbatim and pass this guard unchanged (no regression).
      if (local && local.ok && !isStaticMiss(local, servedPath)) {
        return new Response(local.body, {
          status: 200,
          headers: {
            'content-type': local.headers.get('content-type') || 'application/octet-stream',
            'x-replay-source': 'ext-asset',
          },
        });
      }
    } catch (err) {
      /* fall through to live network */
    }
  }
  try {
    return await fetch(request);
  } catch (err) {
    return new Response(null, { status: 504, headers: { 'x-replay-source': 'ext-miss' } });
  }
}

// ===========================================================================
// STATEFUL CANVAS MOCK (additive). Lazily seeded from the recorded canvas GET,
// then mutated in-memory so the real Tempo bundle can create / move / edit /
// connect / delete nodes and edges entirely offline. Nothing here reaches the
// live backend. Inert for every non-canvas request: handleCanvas returns null
// unless the path is a canvas endpoint, so all existing read-replay behaviour
// is untouched (strict no-regression).
//
// The bundle is NOT optimistic for create/connect/delete — it reads the
// response body and only mutates its React state when { success:true } plus the
// echoed object is present. So each handler echoes the SHAPE the bundle parses.
// ===========================================================================

const CANVAS_GENERATED_IMAGE_URL =
  'https://draperfiles.blob.core.windows.net/brand-assets/39066cbf-78de-4197-bb9b-deb842c27ffa/ads/44bb3425-5a1f-45a2-aca2-18f02549d772.png';

// Per-type input/output ports (mirrors the recorded port-status shape) so the
// bundle can render port handles + validate connections for nodes the store
// creates (which have no recorded port-status of their own).
const CANVAS_PORTS = {
  concept: { input: ['text_prompt', 'product', 'reference_design'], output: ['concept'] },
  text_prompt: { input: ['concept', 'product', 'reference_design'], output: ['text_prompt'] },
  product: { input: ['concept', 'text_prompt'], output: ['product'] },
  reference_design: { input: [], output: ['reference_design'] },
  persona: { input: [], output: ['persona'] },
  image: {
    input: ['concept', 'text_prompt', 'persona', 'product', 'reference_design', 'image', 'experiment'],
    output: ['image'],
  },
};

function canvasUuid() {
  if (self.crypto && self.crypto.randomUUID) return self.crypto.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

// One store per canvas id. { graph: <canvas-GET body>, seeded: bool }.
const CANVAS_STORES = {};
let SERVED_CANVAS = 0;

function parseCanvasPath(pathname) {
  // /api/v1/project/{pid}/canvas[...]
  const m = pathname.match(/\\/api\\/v1\\/project\\/([^/]+)\\/canvas(?:\\/([^/]+))?(?:\\/(.*))?$/);
  if (!m) return null;
  return { projectId: m[1], canvasOrSub: m[2] || '', rest: m[3] || '' };
}

// Seed a canvas store from the recorded GET body for that project. Returns the
// graph object (live store), or null when there is no usable recording.
function seedCanvasStore(projectId) {
  const recPath = '/api/v1/project/' + projectId + '/canvas';
  const rec = pickRecording('GET', recPath, '');
  if (!rec || !rec.body) return null;
  let graph;
  try {
    graph = JSON.parse(rec.body);
  } catch (err) {
    return null;
  }
  if (!graph || !graph.canvas || !Array.isArray(graph.nodes)) return null;
  if (!Array.isArray(graph.edges)) graph.edges = [];
  if (!Array.isArray(graph.groups)) graph.groups = [];
  const cid = graph.canvas.id;
  CANVAS_STORES[cid] = { projectId, graph };
  return graph;
}

function getCanvasStoreByProject(projectId) {
  for (const cid of Object.keys(CANVAS_STORES)) {
    if (CANVAS_STORES[cid].projectId === projectId) return CANVAS_STORES[cid];
  }
  const graph = seedCanvasStore(projectId);
  return graph ? CANVAS_STORES[graph.canvas.id] : null;
}

function getCanvasStoreByCanvasId(canvasId, projectId) {
  if (CANVAS_STORES[canvasId]) return CANVAS_STORES[canvasId];
  // Seed from the project recording (the recorded canvas owns this id).
  if (projectId) {
    const graph = seedCanvasStore(projectId);
    if (graph && graph.canvas.id === canvasId) return CANVAS_STORES[canvasId];
    if (graph) return CANVAS_STORES[graph.canvas.id];
  }
  return null;
}

function canvasJson(body, status) {
  return new Response(JSON.stringify(body), {
    status: status || 200,
    headers: { 'content-type': 'application/json', 'x-replay-source': 'canvas-store' },
  });
}

// Build a full node envelope for a created node, merging the type defaults with
// whatever the bundle sent in data.
function buildNode(canvasId, spec) {
  const type = spec.type;
  const data = Object.assign({ type: type }, spec.data || {});
  data.type = type;
  // image nodes carry richer defaults already in spec.data; ensure arrays exist.
  if (type === 'image') {
    if (!Array.isArray(data.images)) data.images = [];
    if (!Array.isArray(data.uploaded_images)) data.uploaded_images = [];
  }
  if (type === 'reference_design' && !Array.isArray(data.images)) data.images = [];
  if (type === 'product' && !Array.isArray(data.commerce_platform_item_ids)) {
    data.commerce_platform_item_ids = [];
  }
  return {
    id: canvasUuid(),
    canvas_id: canvasId,
    position_x: typeof spec.position_x === 'number' ? spec.position_x : 0,
    position_y: typeof spec.position_y === 'number' ? spec.position_y : 0,
    label: spec.label || data.label || type,
    type: type,
    data: data,
    is_groupable: type === 'image',
    group_id: null,
    group_order: 0,
    connected_ports: null,
    data_source: null,
    data_source_apply_mode: null,
    data_source_group_id: null,
    active_execution: null,
    auto_generate: false,
  };
}

function portStatusForNode(node) {
  const ports = CANVAS_PORTS[node.type] || { input: [], output: [node.type] };
  return {
    node_id: node.id,
    node_type: node.type,
    input_ports: ports.input.map((pt) => ({
      port_type: pt,
      is_required: false,
      connection_mode: 'none',
      sources: [],
      available_upstream: [],
      excluded: [],
    })),
    output_ports: ports.output.slice(),
  };
}

// Pending generate jobs: job_session_id -> { canvasId, nodeId, polls, imageId }.
const CANVAS_JOBS = {};

/**
 * Canvas mutation router. Returns a Response for any canvas endpoint the store
 * owns, or null for a canvas path it does not handle (so the recording / empty
 * fallback answers) and for every non-canvas request (so nothing regresses).
 */
function handleCanvas(method, url, bodyKey, rawBody) {
  const parsed = parseCanvasPath(url.pathname);
  if (!parsed) return null;
  const { projectId, canvasOrSub, rest } = parsed;

  // GET /project/{pid}/canvas — serve the LIVE store (seed on first read).
  if (method === 'GET' && canvasOrSub === '' && rest === '') {
    const store = getCanvasStoreByProject(projectId);
    if (!store) return null; // no recording to seed from -> let recordings answer
    SERVED_CANVAS++;
    return canvasJson(store.graph, 200);
  }

  // PUT /project/{pid}/canvas — whole-graph save (move / edit / delete flush).
  // Two bundle consumers read this response: one ignores the body (validateStatus
  // 200), the other reads back the FULL graph (a.canvas.id, a.canvas.viewport_*,
  // a.project_name, a.nodes/edges/groups) and toasts "Failed to save canvas" when
  // a.canvas is absent. So echo the live graph (same shape as the canvas GET).
  if (method === 'PUT' && canvasOrSub === '' && rest === '') {
    const store = getCanvasStoreByProject(projectId);
    if (!store) return null;
    applyCanvasPut(store, rawBody);
    SERVED_CANVAS++;
    return canvasJson(store.graph, 200);
  }

  // Everything below is /canvas/{cid}/...  -> canvasOrSub is the canvas id.
  const canvasId = canvasOrSub;
  if (!canvasId) return null;
  const store = getCanvasStoreByCanvasId(canvasId, projectId);
  if (!store) return null;

  // node-actions-status is /canvas/node-actions-status (no real canvas id).
  if (canvasId === 'node-actions-status') {
    return handleNodeActionsStatus(projectId, bodyKey);
  }

  // POST /canvas/{cid}/nodes/port-status
  if (method === 'POST' && rest === 'nodes/port-status') {
    let ids = [];
    try {
      const b = JSON.parse(rawBody);
      ids = Array.isArray(b.node_ids) ? b.node_ids : [];
    } catch (err) {
      ids = [];
    }
    const statuses = {};
    for (const node of store.graph.nodes) {
      if (ids.length === 0 || ids.indexOf(node.id) !== -1) {
        statuses[node.id] = portStatusForNode(node);
      }
    }
    SERVED_CANVAS++;
    return canvasJson({ statuses: statuses }, 200);
  }

  // POST /canvas/{cid}/nodes — create node(s). Echo { success, nodes:[...] }.
  if (method === 'POST' && rest === 'nodes') {
    let specs = [];
    try {
      const b = JSON.parse(rawBody);
      specs = Array.isArray(b) ? b : [b];
    } catch (err) {
      specs = [];
    }
    const created = specs.map((s) => buildNode(store.graph.canvas.id, s));
    for (const node of created) store.graph.nodes.push(node);
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true, nodes: created }, 200);
  }

  // POST /canvas/{cid}/edges — create edge(s). Echo { success, edges:[...] }.
  if (method === 'POST' && rest === 'edges') {
    let specs = [];
    try {
      const b = JSON.parse(rawBody);
      specs = Array.isArray(b) ? b : [b];
    } catch (err) {
      specs = [];
    }
    const created = specs.map((s) => ({
      id: canvasUuid(),
      canvas_id: store.graph.canvas.id,
      source_node_id: s.source_node_id,
      target_node_id: s.target_node_id,
      source_port: s.source_port || null,
      target_port: s.target_port || null,
    }));
    for (const edge of created) store.graph.edges.push(edge);
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true, edges: created }, 200);
  }

  // DELETE /canvas/{cid}/nodes/{nid} — remove node + its edges.
  if (method === 'DELETE' && /^nodes\\/[^/]+$/.test(rest)) {
    const nid = rest.split('/')[1];
    store.graph.nodes = store.graph.nodes.filter((n) => n.id !== nid);
    store.graph.edges = store.graph.edges.filter(
      (e) => e.source_node_id !== nid && e.target_node_id !== nid,
    );
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true }, 200);
  }

  // DELETE /canvas/{cid}/edges/{eid}
  if (method === 'DELETE' && /^edges\\/[^/]+$/.test(rest)) {
    const eid = rest.split('/')[1];
    store.graph.edges = store.graph.edges.filter((e) => e.id !== eid);
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true }, 200);
  }

  // PATCH/PUT /canvas/{cid}/node/{nid} — single-node update (merge + echo node).
  if ((method === 'PATCH' || method === 'PUT') && /^node\\/[^/]+$/.test(rest)) {
    const nid = rest.split('/')[1];
    const node = store.graph.nodes.find((n) => n.id === nid);
    if (!node) return canvasJson({ success: false, error: 'Node not found' }, 404);
    let patch = {};
    try {
      patch = JSON.parse(rawBody) || {};
    } catch (err) {
      patch = {};
    }
    if (typeof patch.position_x === 'number') node.position_x = patch.position_x;
    if (typeof patch.position_y === 'number') node.position_y = patch.position_y;
    if (typeof patch.label === 'string') node.label = patch.label;
    if (patch.data && typeof patch.data === 'object') {
      node.data = Object.assign({}, node.data, patch.data);
    }
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true, node: node }, 200);
  }

  // POST /canvas/{cid}/node/{nid}/perform-action[-stream] — generate (mock).
  if (method === 'POST' && /^node\\/[^/]+\\/perform-action(-stream)?$/.test(rest)) {
    const nid = rest.split('/')[1];
    return startCanvasGenerate(store, nid, rest.indexOf('-stream') !== -1);
  }

  // Groups (create / delete) — echo success so group ops don't error.
  if (method === 'POST' && rest === 'groups') {
    const group = { id: canvasUuid(), canvas_id: store.graph.canvas.id };
    try {
      const b = JSON.parse(rawBody);
      Object.assign(group, b && typeof b === 'object' ? b : {});
    } catch (err) {
      /* keep minimal group */
    }
    store.graph.groups.push(group);
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true, groups: [group] }, 200);
  }
  if (method === 'DELETE' && /^groups\\/[^/]+$/.test(rest)) {
    const gid = rest.split('/')[1];
    store.graph.groups = store.graph.groups.filter((g) => g.id !== gid);
    bumpCanvasVersion(store);
    SERVED_CANVAS++;
    return canvasJson({ success: true }, 200);
  }

  return null; // unhandled canvas sub-path -> recordings / empty fallback
}

function bumpCanvasVersion(store) {
  if (store.graph.canvas && typeof store.graph.canvas.version === 'number') {
    store.graph.canvas.version += 1;
  }
  if (store.graph.canvas) store.graph.canvas.updated_at = new Date().toISOString();
}

// Apply the whole-graph PUT to the store: replace viewport, node positions /
// data, and the edge/group sets. New nodes the PUT introduces (with an id the
// store lacks) are appended; nodes the PUT omits are removed (delete flush).
function applyCanvasPut(store, rawBody) {
  let payload;
  try {
    payload = JSON.parse(rawBody);
  } catch (err) {
    return;
  }
  if (!payload || typeof payload !== 'object') return;
  const canvas = store.graph.canvas;
  if (canvas) {
    if (typeof payload.viewport_x === 'number') canvas.viewport_x = payload.viewport_x;
    if (typeof payload.viewport_y === 'number') canvas.viewport_y = payload.viewport_y;
    if (typeof payload.viewport_zoom === 'number') canvas.viewport_zoom = payload.viewport_zoom;
  }
  if (Array.isArray(payload.nodes)) {
    const byId = {};
    for (const n of store.graph.nodes) byId[n.id] = n;
    const next = [];
    for (const incoming of payload.nodes) {
      const existing = byId[incoming.id];
      if (existing) {
        if (typeof incoming.position_x === 'number') existing.position_x = incoming.position_x;
        if (typeof incoming.position_y === 'number') existing.position_y = incoming.position_y;
        if (typeof incoming.label === 'string') existing.label = incoming.label;
        if (incoming.data && typeof incoming.data === 'object') {
          existing.data = Object.assign({}, existing.data, incoming.data);
        }
        if (typeof incoming.auto_generate === 'boolean') existing.auto_generate = incoming.auto_generate;
        next.push(existing);
      } else {
        next.push(buildNode(canvas ? canvas.id : '', incoming));
      }
    }
    store.graph.nodes = next;
  }
  if (Array.isArray(payload.edges)) {
    // Keep store edges that the PUT still references; the bundle sends edges by
    // id once created, so honour the incoming set when it is non-trivial.
    store.graph.edges = payload.edges.map((e) => ({
      id: e.id || canvasUuid(),
      canvas_id: canvas ? canvas.id : '',
      source_node_id: e.source_node_id,
      target_node_id: e.target_node_id,
      source_port: e.source_port || null,
      target_port: e.target_port || null,
    }));
  }
  if (Array.isArray(payload.groups)) store.graph.groups = payload.groups;
  bumpCanvasVersion(store);
}

// Begin a synthetic generate job: register a session, inject a placeholder
// image into the node after a couple of polls, and report completion via
// node-actions-status. No real backend, clearly marked is_generated mock.
function startCanvasGenerate(store, nodeId, isStream) {
  const node = store.graph.nodes.find((n) => n.id === nodeId);
  const jobSessionId = canvasUuid();
  const executionId = canvasUuid();
  const imageId = canvasUuid();
  CANVAS_JOBS[jobSessionId] = {
    canvasId: store.graph.canvas.id,
    nodeId: nodeId,
    polls: 0,
    imageId: imageId,
    injected: false,
  };
  SERVED_CANVAS++;
  const result = {
    success: true,
    job_session_id: jobSessionId,
    job_id: jobSessionId,
    execution_id: executionId,
    message: 'Generation started (replay mock).',
  };
  if (isStream) {
    // Minimal SSE: one frame echoing the job ids, then done.
    const frame =
      'data: ' + JSON.stringify({ type: 'started', job_session_id: jobSessionId }) + '\\n\\n';
    return new Response(frame, {
      status: 200,
      headers: { 'content-type': 'text/event-stream', 'x-replay-source': 'canvas-store' },
    });
  }
  // Pre-mark the node so a refetch even before the first poll shows progress.
  if (node) node.active_execution = { execution_id: executionId, status: 'running' };
  return canvasJson(result, 200);
}

// node-actions-status poll. After >=1 poll, mark the job finished and inject a
// mock placeholder image into the node's data.images so the generate UX paints.
function handleNodeActionsStatus(projectId, bodyKey) {
  let ids = [];
  try {
    const b = JSON.parse(bodyKey);
    ids = Array.isArray(b.job_session_ids) ? b.job_session_ids : [];
  } catch (err) {
    ids = [];
  }
  const statuses = {};
  for (const jid of ids) {
    const job = CANVAS_JOBS[jid];
    if (!job) {
      statuses[jid] = { is_finished: true, success: true, error: null, progress: null };
      continue;
    }
    job.polls += 1;
    const finished = job.polls >= 1;
    if (finished && !job.injected) {
      injectMockImage(job);
      job.injected = true;
    }
    statuses[jid] = {
      is_finished: finished,
      success: true,
      error: null,
      progress: {
        created_image_ids: finished ? [job.imageId] : [],
        completed_node_ids: finished ? [job.nodeId] : [],
      },
    };
  }
  SERVED_CANVAS++;
  return canvasJson({ statuses: statuses }, 200);
}

function injectMockImage(job) {
  const store = CANVAS_STORES[job.canvasId];
  if (!store) return;
  const node = store.graph.nodes.find((n) => n.id === job.nodeId);
  if (!node || !node.data) return;
  if (!Array.isArray(node.data.images)) node.data.images = [];
  node.data.images.push({
    id: job.imageId,
    image_asset_id: canvasUuid(),
    url: CANVAS_GENERATED_IMAGE_URL,
    is_active: true,
    is_generated: true,
    is_mock: true, // mark clearly: replay placeholder, not real AI output
    generation_prompt: node.data.generate_prompt || '',
    edit_prompt: '',
    aspect_ratio:
      Array.isArray(node.data.aspect_ratios) && node.data.aspect_ratios[0]
        ? node.data.aspect_ratios[0]
        : 'square_1_1',
    parent_image_id: null,
    display_order: node.data.images.length,
    text_elements: [],
    text_elements_extracted: false,
  });
  node.active_execution = null;
  bumpCanvasVersion(store);
}

${enableViewSynth ? VIEW_SYNTH_HANDLER_SOURCE : ''}
${fuzzyHelpersSource}
async function handleApi(request, url, clientId) {
  await recordingsReady;
  const method = request.method.toUpperCase();
  let rawBody = '';
  let bodyKey = '';
  if (method !== 'GET' && method !== 'HEAD') {
    try {
      rawBody = await request.clone().text();
      bodyKey = normalizeBody(rawBody);
    } catch (err) {
      bodyKey = '';
    }
  }

  // 0. BACKEND-FIRST when an OWNED backend is wired (additive, no-regression).
  // With BACKEND_URL set, the OWNED backend is the source of truth: it serves
  // every live /api/v1 read AND persists canvas/generation WRITES to its DB, so
  // edits survive a reload (the whole point of wiring a real backend). We try it
  // BEFORE the in-SW canvas mock so a canvas write hits the DB instead of being
  // shadowed by SW-memory state. A backend MISS / error returns null and we fall
  // through to the canvas mock + recordings below, so an uncovered path still
  // works. When BACKEND_URL is empty this is inert (tryBackend short-circuits),
  // so the offline replay (canvas mock + recordings) is unchanged.
  if (BACKEND_URL) {
    const liveFirst = await tryBackend(request, url, method, rawBody);
    if (liveFirst) return liveFirst;
  }

  // 0a. STATEFUL CANVAS MOCK (additive, no-regression). The in-memory canvas store
  // owns every canvas mutation + the canvas GET refetch so the bundle can create /
  // move / edit / connect / delete / generate offline. Returns null for any
  // non-canvas request and for canvas sub-paths it does not handle, so all
  // existing recording / backend / empty-200 behaviour is untouched. Runs after
  // the backend (when wired) so the DB owns canvas state; with no backend it runs
  // first for canvas paths so the live store shadows the (now stale) recorded GET.
  const canvasRes = handleCanvas(method, url, bodyKey, rawBody);
  if (canvasRes) return canvasRes;

  // 0a. CAPTURED-VIEW GUARD (additive, no-regression). A genericView request for
  // a parent that HAS a captured view-shaped payload is served from that capture,
  // NOT the backend. The backend's genericView handler is list-shaped (no
  // board.groups / no calendar block); a board or calendar view needs its own
  // captured shape, which the backend cannot synthesize. We route by parent id —
  // robust against volatile body fields (cache vectors, timestamps) that defeat
  // an exact body-key match. Lists the backend serves have NO captured genericView
  // for their dynamic body, so they fall through to the backend exactly as before.
  const rec = pickRecording(method, url.pathname, bodyKey);
  const reqParent = genericViewParentId(method, url.pathname, bodyKey);
  if (reqParent) {
    const byParent = RECORDINGS.filter(
      (r) =>
        r.method === method &&
        pathMatches(url.pathname, r.pathPattern) &&
        r.body &&
        r.body.length > 2 &&
        genericViewParentId(method, url.pathname, r.requestBodyKey) === reqParent,
    );
    if (byParent.length > 0) {
      const exact = byParent.find((r) => r.requestBodyKey === bodyKey);
      return recordedResponse(exact || byParent[0]);
    }
  }
  // An exact body-key capture for any other view-data request is authoritative.
  if (rec && bodyKey && rec.requestBodyKey === bodyKey && rec.body && rec.body.length > 2) {
    return recordedResponse(rec);
  }

  // 0a2. VIZ-VIEW GUARD (additive, no-regression). A GET viz/v1/view/{id} that
  // has a REAL 200 recording (the handful of views the crawl actually captured)
  // is served from that recording, NOT the synthesizer — the recorded per-view
  // body is the ground truth and richer than a re-populated template. The synth
  // backend only fills the gap for views with NO 200 recording (the 404 siblings
  // and every uncaptured view), so the 5 already-rendering views never regress.
  if (method === 'GET' && /\\/viz\\/v1\\/view\\/[^/]+$/.test(url.pathname)) {
    if (rec && rec.status >= 200 && rec.status < 300 && rec.body && rec.body.length > 2) {
      return recordedResponse(rec);
    }
  }

  // 0a3. VIEW-SYNTH FALLBACK (additive, no-regression). Only fires when
  // SYNTH_TEMPLATES is non-empty (ClickUp profile, viewSynth.enabled=true).
  // Runs AFTER exact recordings (those always win per the VIZ-VIEW GUARD
  // above). Synthesises a 200 from a per-type template for views the crawl
  // never captured. Returns null on miss → falls through to recordings /
  // empty-200 exactly as before. Inert for every non-ClickUp build.
  ${enableViewSynth ? `{
    const synthRes = await synthViewResponse(url, request, SYNTH_TEMPLATES, clientId);
    if (synthRes) return synthRes;
  }` : '/* view-synth disabled for this profile */'}

  // 0a4. FUZZY POST-BODY MATCH (additive, no-regression). Only fires when:
  //   - profile.fuzzyBodyMatch.enabled = true (compile-time gate)
  //   - method is POST + the request has a JSON body
  //   - exact body-key match against same-path candidates missed
  // Scores every same-path candidate via structural similarity (normalised
  // bodies, Levenshtein-or-length-delta). Returns the best candidate above
  // the endpoint-class threshold. Falls through to the existing richest-body
  // fallback below when no candidate clears the threshold — strict no-regression.
  ${fuzzyEnabled ? `
  if (method === 'POST' && bodyKey) {
    const fuzzyCandidates = RECORDINGS.filter(
      (r) => r.method === 'POST' && pathMatches(url.pathname, r.pathPattern),
    );
    const hasExact = fuzzyCandidates.some((r) => r.requestBodyKey === bodyKey);
    if (!hasExact && fuzzyCandidates.length > 0) {
      let parsedIncoming = null;
      try { parsedIncoming = JSON.parse(rawBody); } catch (e) { parsedIncoming = null; }
      if (parsedIncoming !== null) {
        const fuzzy = fuzzyMatchBody(url.pathname, parsedIncoming, fuzzyCandidates);
        if (fuzzy && fuzzy.candidate.body && fuzzy.candidate.body.length > 2) {
          SERVED_RECORDING++;
          return new Response(fuzzy.candidate.body, {
            status: fuzzy.candidate.status,
            headers: {
              'content-type': fuzzy.candidate.contentType || 'application/json',
              'x-replay-source': 'fuzzy-body-match',
              'x-fuzzy-score': String(fuzzy.score.toFixed(3)),
              'x-fuzzy-class': fuzzy.endpointClass,
            },
          });
        }
      }
    }
  }
  ` : '/* fuzzy-body-match disabled for this profile */'}

  // 0b. ADDITIVE: forward to the OWNED local backend (live dynamic reads).
  // When BACKEND_URL is set this already ran backend-first at step 0 (no second
  // round-trip), so this only fires the legacy path: a non-empty backend that
  // the captured-view guards above let through. A backend MISS or error returns
  // null and we fall through to recordings; inert when BACKEND_URL is empty.
  if (!BACKEND_URL) {
    const live = await tryBackend(request, url, method, rawBody);
    if (live) return live;
  }

  if (rec) return recordedResponse(rec);

  const fallback = unrecordedApiResponse(method);
  if (fallback) return fallback;

  // bypass mode: let it hit the network (will fail offline, by design).
  try {
    return await fetch(request);
  } catch (err) {
    return new Response('{}', {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
}

${enableDocFreeze ? `
// DOC-FREEZE: short-circuit every HTTP request to a Codox host. The captured
// content has already been frozen into the editor by the doc-freezer shim, so
// the live Codox auth/CDN chain has nothing to deliver — returning empty 200s
// keeps the SPA from hanging on retries / loading spinners. Inert when
// enableDocFreeze=false (no regression).
var CODOX_HOST_RE = /(^|\\.)codox\\.io$|coeditor\\.clickup\\.com$/i;
function isCodoxHost(host) { return CODOX_HOST_RE.test(host); }
function codoxStubResponse() {
  return new Response('{}', {
    status: 200,
    headers: { 'content-type': 'application/json', 'x-replay-source': 'codox-block' },
  });
}
` : ''}

async function handle(request, clientId) {
  const url = new URL(request.url);
  const sameOrigin = url.origin === self.location.origin;

  ${enableDocFreeze ? `// DOC-FREEZE codox short-circuit (additive, no-regression).
  if (isCodoxHost(url.host)) return codoxStubResponse();` : '/* doc-freeze disabled for this profile */'}

  // Same-origin static asset (localized bundle/CSS/font/image OR a lazy chunk
  // the bundle requests): serve from disk, stubbing 404s so boot survives.
  if (sameOrigin && (isLocalAsset(url.pathname) || looksStatic(url.pathname))) {
    return handleStatic(request, url.pathname);
  }

  // Cross-origin static asset (ad/project creatives + fonts on a captured CDN
  // host, referenced by absolute URL inside recorded JSON bodies): serve the
  // localized _ext copy, falling through to the live network on a local miss.
  // Also covers EXTENSIONLESS image URLs (e.g. Google profile avatars at
  // lh3.googleusercontent.com/a/<id>=s96-c) — the path has no .png so looksStatic
  // is false, but the browser requests it as an image (Accept: image/...). The
  // localized _ext copy still resolves; on a miss we fall through to live network.
  if (
    !sameOrigin &&
    request.method === 'GET' &&
    (looksStatic(url.pathname) || acceptsImage(request))
  ) {
    return handleCrossOriginStatic(request, url);
  }

  return handleApi(request, url, clientId);
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Let the browser load the rewritten bootstrap HTML directly.
  if (req.mode === 'navigate') return;
  event.respondWith(handle(req, event.clientId));
});

// Probe hook: a client posts { type: 'replay-stats' } and the SW replies with
// the served-from-recording vs served-empty-200 counts on the message port.
self.addEventListener('message', (event) => {
  if (!event.data || event.data.type !== 'replay-stats') return;
  const stats = { servedRecording: SERVED_RECORDING, servedEmpty200: SERVED_EMPTY200 };
  if (event.ports && event.ports[0]) event.ports[0].postMessage(stats);
});
`;
}
