/**
 * Emit the replay Service Worker source. Emitted at the ORIGIN ROOT (`/sw.js`)
 * so its default scope is `/` and it controls the whole origin: the page, the
 * app bundle, and every `/_ext/...` asset request. It intercepts EVERY fetch
 * and answers API calls from `recordings.json`.
 *
 * API matching mirrors the emit-mocks handler semantics:
 *   method + templated path (numeric / hex id segments wildcarded) + optional
 *   request-body branch. Unrecorded API requests fall back per `unrecordedMode`:
 *   'empty-200' returns `{}` as 200 JSON (keeps the app alive, avoids login
 *   bounces / hung promises); 'bypass' lets the request hit the real network.
 *
 * Same-origin STATIC requests (the bundle, CSS, fonts, images, media, and the
 * code-split chunks the app lazy-loads) are served from the static file server.
 * When a static request 404s — a lazy chunk / asset the crawl never captured —
 * the SW returns a graceful empty stub with the RIGHT content-type (empty JS
 * module for *.js, empty CSS for *.css, empty body for media) so a missing
 * lazy chunk does not hard-crash the bundle.
 *
 * The SW is plain JS (no bundler) so the emitted project runs under `npx serve`
 * with zero install step.
 */

import type { UnrecordedMode } from './types';

const LOCAL_ASSET_PREFIXES = ['/_ext/', '/_external/', '/media/', '/assets/'];

export function buildServiceWorker(unrecordedMode: UnrecordedMode): string {
  return `/**
 * Auto-generated by dr-parity replay target. Intercepts fetch and answers from
 * recorded traffic. Do not edit by hand: re-run build:replay to regenerate.
 */
/* eslint-disable */
'use strict';

const UNRECORDED_MODE = ${JSON.stringify(unrecordedMode)};
const LOCAL_ASSET_PREFIXES = ${JSON.stringify(LOCAL_ASSET_PREFIXES)};

let RECORDINGS = [];
let recordingsReady = (async () => {
  try {
    const res = await fetch('/replay/recordings.json', { cache: 'no-store' });
    RECORDINGS = await res.json();
  } catch (err) {
    RECORDINGS = [];
  }
})();

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

function isLocalAsset(pathname) {
  return LOCAL_ASSET_PREFIXES.some((p) => pathname.startsWith(p));
}

function segmentize(pathname) {
  return pathname.split('/').filter((s) => s.length > 0);
}

/** Mirror emit-mocks id-segment wildcarding: numeric or 8+ hex segments => '*'. */
function normalizedSegments(pathname) {
  return segmentize(pathname).map((s) =>
    /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function patternToSegments(pattern) {
  // emit-mocks emits ':param' placeholders for multi-capture wildcard segments,
  // but a single-capture group keeps the literal id segment. Wildcard both so a
  // request whose id segment we normalized to '*' still matches.
  return segmentize(pattern).map((s) =>
    s.startsWith(':') || /^[0-9]+$|^[0-9a-f]{8,}$/i.test(s) ? '*' : s,
  );
}

function pathMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (reqSegs.length !== patSegs.length) return false;
  for (let i = 0; i < patSegs.length; i++) {
    if (patSegs[i] === '*') continue;
    if (patSegs[i] !== reqSegs[i]) return false;
  }
  return true;
}

/**
 * Looser fallback: does the recorded pattern's normalized segment list match a
 * TRAILING slice of the request path? Tolerates a runtime URL that carries one
 * extra LEADING id segment vs the captured pattern (e.g. a regional-shard
 * prefix). Exact match is always tried first in pickRecording; this only runs
 * when nothing matched exactly.
 *
 * IMPORTANT: a head (leading) slice match is deliberately NOT done here. A
 * recorded COLLECTION endpoint (e.g. GET /hierarchy/v1/project — a JSON array
 * of all projects) is a head-slice of a SINGLE-RESOURCE request (e.g. GET
 * /hierarchy/v1/project/901511060743 — one project object, or its /all_statuses
 * sub-resource). Serving the array body for the single-resource request feeds
 * the app a wrong-shaped response and breaks its parser. So we only allow a
 * recorded DEEPER/sibling pattern to answer via a trailing slice, never a
 * shallower collection root.
 */
function pathSubMatches(requestPath, pattern) {
  const reqSegs = normalizedSegments(requestPath);
  const patSegs = patternToSegments(pattern);
  if (patSegs.length === 0 || patSegs.length > reqSegs.length) return false;
  // Trailing-slice match only. Require at least 2 shared non-wildcard segments
  // so we don't over-match on a single generic segment like 'v1'.
  const offset = reqSegs.length - patSegs.length;
  let concreteTail = 0;
  const tailMatch = patSegs.every((s, i) => {
    if (s === '*') return true;
    concreteTail++;
    return s === reqSegs[offset + i];
  });
  return tailMatch && concreteTail >= 2;
}

function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(stableStringify).join(',') + ']';
  const keys = Object.keys(value).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + stableStringify(value[k])).join(',') + '}';
}

function normalizeBody(raw) {
  if (raw === null || raw === undefined || raw === '') return '';
  try {
    return stableStringify(JSON.parse(raw));
  } catch (err) {
    return raw;
  }
}

function chooseFromCandidates(candidates, bodyKey) {
  if (candidates.length === 0) return null;
  // Prefer an exact request-body-branch match, then the first body-less record,
  // then any candidate (so GETs without a body still resolve). Among equally
  // valid candidates, prefer one with a non-empty body so a recorded payload
  // beats a recorded empty/304 sibling.
  const exact = candidates.find((r) => r.requestBodyKey === bodyKey);
  if (exact) return exact;
  const empty = candidates.find((r) => r.requestBodyKey === '');
  if (empty) return empty;
  const withBody = candidates.find((r) => r.body && r.body.length > 2);
  if (withBody) return withBody;
  return candidates[0];
}

function pickRecording(method, pathname, bodyKey) {
  // 1. Exact path match (numeric/hex id segments wildcarded). The strict path.
  const exactPath = RECORDINGS.filter(
    (r) => r.method === method && pathMatches(pathname, r.pathPattern),
  );
  const chosen = chooseFromCandidates(exactPath, bodyKey);
  if (chosen) return chosen;

  // 2. Tolerant fallback: a recorded sibling endpoint whose normalized segment
  // list is a leading/trailing slice of this request path. Serves a recorded
  // body for a near-miss (sub-resource the crawl did not drill into, or a shard
  // prefix) instead of a bare empty-200. Same method only.
  const subPath = RECORDINGS.filter(
    (r) => r.method === method && pathSubMatches(pathname, r.pathPattern),
  );
  return chooseFromCandidates(subPath, bodyKey);
}

// Lightweight served-source counters, readable by a probe via postMessage
// ('replay-stats') or the 'x-replay-source' response header.
let SERVED_RECORDING = 0;
let SERVED_EMPTY200 = 0;

function recordedResponse(rec) {
  SERVED_RECORDING++;
  return new Response(rec.body, {
    status: rec.status,
    headers: {
      'content-type': rec.contentType || 'application/json',
      'x-replay-source': 'recording',
    },
  });
}

function unrecordedApiResponse(method) {
  if (UNRECORDED_MODE === 'bypass') return null;
  // empty-200: keep the app alive. JSON for fetch/XHR; HEAD/OPTIONS get 204.
  if (method === 'OPTIONS' || method === 'HEAD') {
    return new Response(null, {
      status: 204,
      headers: { 'x-replay-source': 'empty' },
    });
  }
  SERVED_EMPTY200++;
  return new Response('{}', {
    status: 200,
    headers: {
      'content-type': 'application/json',
      'x-replay-source': 'empty',
    },
  });
}

const JS_EXT = /\\.(m?js|cjs)$/i;
const CSS_EXT = /\\.css$/i;
const MEDIA_EXT = /\\.(png|jpe?g|gif|svg|webp|avif|ico|woff2?|ttf|otf|eot|wasm|mp4|webm|m4a|mp3|ogg)$/i;

function looksStatic(pathname) {
  return JS_EXT.test(pathname) || CSS_EXT.test(pathname) || MEDIA_EXT.test(pathname);
}

/**
 * Graceful stub for an uncaptured same-origin static asset (a lazy chunk or
 * asset the crawl never recorded). Returns the RIGHT content-type so a missing
 * file does not hard-crash the bundle: empty JS module for *.js, empty CSS for
 * *.css, empty body otherwise.
 */
function staticStub(pathname) {
  if (JS_EXT.test(pathname)) {
    return new Response('export {};\\n', {
      status: 200,
      headers: { 'content-type': 'application/javascript; charset=utf-8' },
    });
  }
  if (CSS_EXT.test(pathname)) {
    return new Response('/* dr-parity replay: uncaptured stylesheet */\\n', {
      status: 200,
      headers: { 'content-type': 'text/css; charset=utf-8' },
    });
  }
  return new Response(null, { status: 200, headers: { 'content-type': 'application/octet-stream' } });
}

/**
 * Serve a same-origin static request from the static file server; on 404 or a
 * network error, fall back to a typed stub so a missing lazy chunk / asset is
 * non-fatal.
 */
async function handleStatic(request, pathname) {
  try {
    const res = await fetch(request);
    if (res && res.status !== 404) return res;
  } catch (err) {
    /* fall through to stub */
  }
  return staticStub(pathname);
}

async function handleApi(request, url) {
  await recordingsReady;
  const method = request.method.toUpperCase();
  let bodyKey = '';
  if (method !== 'GET' && method !== 'HEAD') {
    try {
      bodyKey = normalizeBody(await request.clone().text());
    } catch (err) {
      bodyKey = '';
    }
  }

  const rec = pickRecording(method, url.pathname, bodyKey);
  if (rec) return recordedResponse(rec);

  const fallback = unrecordedApiResponse(method);
  if (fallback) return fallback;

  // bypass mode: let it hit the network (will fail offline, by design).
  try {
    return await fetch(request);
  } catch (err) {
    return new Response('{}', {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
}

async function handle(request) {
  const url = new URL(request.url);
  const sameOrigin = url.origin === self.location.origin;

  // Same-origin static asset (localized bundle/CSS/font/image OR a lazy chunk
  // the bundle requests): serve from disk, stubbing 404s so boot survives.
  if (sameOrigin && (isLocalAsset(url.pathname) || looksStatic(url.pathname))) {
    return handleStatic(request, url.pathname);
  }

  return handleApi(request, url);
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Let the browser load the rewritten bootstrap HTML directly.
  if (req.mode === 'navigate') return;
  event.respondWith(handle(req));
});

// Probe hook: a client posts { type: 'replay-stats' } and the SW replies with
// the served-from-recording vs served-empty-200 counts on the message port.
self.addEventListener('message', (event) => {
  if (!event.data || event.data.type !== 'replay-stats') return;
  const stats = { servedRecording: SERVED_RECORDING, servedEmpty200: SERVED_EMPTY200 };
  if (event.ports && event.ports[0]) event.ports[0].postMessage(stats);
});
`;
}
