/**
 * Emit `src/mocks/socket.ts`. Boot wires each captured connection to a
 * `mock-socket` server that replays its `received` frames on the
 * scheduled offsets, then patches the global `WebSocket` constructor so
 * the cloned app transparently hits the mock.
 *
 * When no groups exist we still emit a no-op module so the app's import
 * site never breaks.
 */

import { importNameForFixture } from './build-fixtures';
import type { ConnectionGroup, RealtimeFixtureFile } from './types';

const EMPTY_BOOT = [
  '/**',
  ' * Auto-generated by dr-parity Phase 5. No websocket traffic was captured',
  ' * during crawl, so these are no-op stubs.',
  ' */',
  '',
  'export function startSocketMocks(): void {',
  '  /* no captured ws frames */',
  '}',
  '',
  'export function stopSocketMocks(): void {',
  '  /* no captured ws frames */',
  '}',
  '',
].join('\n');

export function buildSocketBoot(
  groups: ConnectionGroup[],
  fixtureFiles: RealtimeFixtureFile[],
): string {
  if (groups.length === 0 || fixtureFiles.length === 0) {
    return EMPTY_BOOT;
  }

  const importLines = fixtureFiles.map((file) => {
    const name = importNameForFixture(file.relativePath);
    return `import ${name} from '../fixtures/${file.relativePath.replace(/^src\/fixtures\//, '')}';`;
  });

  const replayRefs = fixtureFiles
    .map((file) => `  ${importNameForFixture(file.relativePath)} as Replay,`)
    .join('\n');
  // Cast per-import to satisfy strict typing of JSON modules (Vite infers
  // narrow string literals from the JSON; we widen to the runtime Replay
  // shape at the boundary).

  return [
    '/**',
    ' * Auto-generated by dr-parity Phase 5. Replays captured server->client',
    " * WebSocket frames against `mock-socket`. The global `WebSocket` is",
    ' * patched so the cloned app connects to the mock without code changes.',
    ' */',
    '',
    "import { Server as MockSocketServer, WebSocket as MockWS } from 'mock-socket';",
    ...importLines,
    '',
    "type Frame = { direction: 'received' | 'sent'; atMs: number; payload: string };",
    'type Replay = {',
    '  url: string;',
    '  urlPattern: string;',
    '  durationMs: number;',
    '  frames: Frame[];',
    '};',
    '',
    'const REPLAYS: Replay[] = [',
    replayRefs,
    '];',
    '',
    'const servers: MockSocketServer[] = [];',
    'const timers: ReturnType<typeof setTimeout>[] = [];',
    '',
    'export function startSocketMocks(): void {',
    '  for (const replay of REPLAYS) {',
    '    const server = new MockSocketServer(replay.url);',
    '    server.on(\'connection\', (socket) => {',
    '      for (const frame of replay.frames) {',
    "        if (frame.direction !== 'received') continue;",
    '        const timer = setTimeout(() => {',
    '          socket.send(frame.payload);',
    '        }, frame.atMs);',
    '        timers.push(timer);',
    '      }',
    '    });',
    '    servers.push(server);',
    '  }',
    '  (globalThis as unknown as { WebSocket: typeof WebSocket }).WebSocket =',
    '    MockWS as unknown as typeof WebSocket;',
    '}',
    '',
    'export function stopSocketMocks(): void {',
    '  for (const timer of timers) clearTimeout(timer);',
    '  timers.length = 0;',
    '  for (const server of servers) server.stop();',
    '  servers.length = 0;',
    '}',
    '',
  ].join('\n');
}

export { EMPTY_BOOT };
