/**
 * Run context construction.
 *
 * Phase 4 scaffold per docs/V2.0/04-cli-and-logging-design.md (Part C, C.2)
 * and docs/V2.0/05-action-plan.md §4 Phase 4 task 4.
 *
 * Generates a run id and a default stdout-backed Logger. Phase 5 wires this
 * to `.runs/<runId>/manifest.json` + `pipeline.jsonl` writers.
 */

import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import type { LogMeta, Logger, MetricValue, RunContext } from "./stage.js";

export interface CreateRunContextOptions {
  /** Override the autogenerated run id (e.g. for resume). */
  readonly runId?: string;
  /** Override the run directory. Default `.runs/<runId>` relative to cwd. */
  readonly outDir?: string;
  /** Inject a custom logger (e.g. silent or json). Default: stdout logger. */
  readonly logger?: Logger;
}

/** ISO timestamp with colons replaced for filesystem safety. */
function isoStampForId(date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, "-");
}

/** 4-character lowercase hex tag for run id disambiguation. */
function shortTag(): string {
  return randomBytes(2).toString("hex");
}

/** Default run id: `<iso>-<rand4>`. Sortable, greppable, unique. */
export function generateRunId(): string {
  return `${isoStampForId()}-${shortTag()}`;
}

/**
 * Stdout logger. Plain text for humans. Phase 5 will swap this for a writer
 * that also emits NDJSON into `.runs/<runId>/pipeline.jsonl`.
 */
function createStdoutLogger(runId: string): Logger {
  const fmt = (meta?: LogMeta): string => {
    if (!meta) return "";
    const keys = Object.keys(meta);
    if (keys.length === 0) return "";
    return ` ${JSON.stringify(meta)}`;
  };

  return {
    info(msg: string, meta?: LogMeta) {
      process.stdout.write(`[${runId}] info  ${msg}${fmt(meta)}\n`);
    },
    warn(msg: string, meta?: LogMeta) {
      process.stdout.write(`[${runId}] warn  ${msg}${fmt(meta)}\n`);
    },
    error(msg: string, meta?: LogMeta) {
      process.stderr.write(`[${runId}] error ${msg}${fmt(meta)}\n`);
    },
    metric(name: string, value: MetricValue, meta?: LogMeta) {
      process.stdout.write(
        `[${runId}] metric ${name}=${String(value)}${fmt(meta)}\n`,
      );
    },
    event(name: string, fields?: LogMeta) {
      process.stdout.write(`[${runId}] event ${name}${fmt(fields)}\n`);
    },
  };
}

export function createRunContext(
  options: CreateRunContextOptions = {},
): RunContext {
  const runId = options.runId ?? generateRunId();
  const outDir = options.outDir ?? resolve(process.cwd(), ".runs", runId);
  const logger = options.logger ?? createStdoutLogger(runId);

  // TODO Phase 5: create `.runs/<runId>/` here, write `manifest.json` seed,
  // open a `pipeline.jsonl` write stream, register a finalize hook that
  // flushes the manifest on process exit. See docs/V2.0/04-cli-and-logging-design.md
  // Part C sections C.2 and D.

  return {
    runId,
    outDir,
    logger,
    startedAt: Date.now(),
  };
}
