/**
 * Run context construction.
 *
 * Phase 5 implementation per docs/V2.0/04-cli-and-logging-design.md (Part C, C.2)
 * and docs/V2.0/05-action-plan.md §4 Phase 5 task 1.
 *
 * Creates `.runs/<runId>/` plus its subdirs, opens a `pipeline.jsonl` writer,
 * and returns a RunContext whose Logger tees structured events to:
 *   1. the JSONL event stream
 *   2. stdout/stderr for the human terminal
 *   3. per-stage stage-log files (when `.forStage(name)` is used)
 */

import { randomBytes } from "node:crypto";
import { promises as fs } from "node:fs";
import { createWriteStream, type WriteStream } from "node:fs";
import { resolve, join } from "node:path";
import {
  createEventStream,
  nowIso,
  type EventStreamWriter,
  type PipelineEvent,
} from "./event-stream.js";
import type {
  DisposeFn,
  LogMeta,
  Logger,
  MetricValue,
  RunContext,
} from "./stage.js";

export interface CreateRunContextOptions {
  /** Override the autogenerated run id (e.g. for resume). */
  readonly runId?: string;
  /** Override the run directory. Default `.runs/<runId>` relative to cwd. */
  readonly outDir?: string;
  /** Disable file writes; only stdout. Useful for tests. */
  readonly noFiles?: boolean;
}

/**
 * Extended RunContext returned to callers that need to push events directly
 * (e.g. the orchestrator) or finalise the run. Subagent stages only see the
 * structural `RunContext`.
 */
export interface FullRunContext extends RunContext {
  /** Emit a structured event into the JSONL stream. */
  emit(event: PipelineEvent): void;
  /** Returns a Logger scoped to a stage; its writes ALSO land in stage-logs/<stage>.log. */
  forStage(stage: string): Logger;
  /** Run all registered disposers (LIFO), close the event stream. */
  finalise(): Promise<void>;
  /** Register a cleanup function. LIFO order. */
  onDispose(fn: DisposeFn): void;
}

/** ISO timestamp with colons replaced for filesystem safety. */
function isoStampForId(date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, "-");
}

/** 4-character lowercase hex tag for run id disambiguation. */
function shortTag(): string {
  return randomBytes(2).toString("hex");
}

/** Default run id: `<iso>-<rand4>`. Sortable, greppable, unique. */
export function generateRunId(): string {
  return `${isoStampForId()}-${shortTag()}`;
}

function fmtMeta(meta?: LogMeta): string {
  if (!meta) return "";
  const keys = Object.keys(meta);
  if (keys.length === 0) return "";
  return ` ${JSON.stringify(meta)}`;
}

interface StageLogStreams {
  readonly logFile: WriteStream;
}

/**
 * Open the per-stage log file lazily on first write so stages that never
 * log do not litter the disk with empty files.
 */
function openStageLog(runDir: string, stage: string): StageLogStreams {
  const path = join(runDir, "stage-logs", `${stage}.log`);
  const logFile = createWriteStream(path, { flags: "a" });
  return { logFile };
}

export async function createRunContext(
  options: CreateRunContextOptions = {},
): Promise<FullRunContext> {
  const runId = options.runId ?? generateRunId();
  const outDir = options.outDir ?? resolve(process.cwd(), ".runs", runId);
  const noFiles = options.noFiles ?? false;

  if (!noFiles) {
    await fs.mkdir(outDir, { recursive: true });
    await fs.mkdir(join(outDir, "stage-logs"), { recursive: true });
  }

  const eventStream: EventStreamWriter | null = noFiles
    ? null
    : createEventStream(join(outDir, "pipeline.jsonl"));

  const stageStreams = new Map<string, StageLogStreams>();
  const disposers: DisposeFn[] = [];

  const emit = (event: PipelineEvent): void => {
    eventStream?.emit(event);
  };

  const writeStageLog = (stage: string, line: string): void => {
    if (noFiles) return;
    let streams = stageStreams.get(stage);
    if (!streams) {
      streams = openStageLog(outDir, stage);
      stageStreams.set(stage, streams);
    }
    streams.logFile.write(`${line}\n`);
  };

  /** Root logger: writes to stdout/stderr plus JSONL. No stage attribution. */
  const rootLogger: Logger = {
    info(msg, meta) {
      process.stdout.write(`[${runId}] info  ${msg}${fmtMeta(meta)}\n`);
      emit({
        type: "log",
        stage: "run",
        at: nowIso(),
        level: "info",
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    warn(msg, meta) {
      process.stdout.write(`[${runId}] warn  ${msg}${fmtMeta(meta)}\n`);
      emit({
        type: "warning",
        stage: "run",
        at: nowIso(),
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    error(msg, meta) {
      process.stderr.write(`[${runId}] error ${msg}${fmtMeta(meta)}\n`);
      emit({
        type: "error",
        stage: "run",
        at: nowIso(),
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    metric(name, value, meta) {
      process.stdout.write(
        `[${runId}] metric ${name}=${String(value)}${fmtMeta(meta)}\n`,
      );
      emit({
        type: "metric",
        stage: "run",
        at: nowIso(),
        name,
        value,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    event(name, fields) {
      process.stdout.write(`[${runId}] event ${name}${fmtMeta(fields)}\n`);
    },
  };

  const forStage = (stage: string): Logger => ({
    info(msg, meta) {
      const line = `info  ${msg}${fmtMeta(meta)}`;
      process.stdout.write(`[${runId}] ${stage} ${line}\n`);
      writeStageLog(stage, line);
      emit({
        type: "log",
        stage,
        at: nowIso(),
        level: "info",
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    warn(msg, meta) {
      const line = `warn  ${msg}${fmtMeta(meta)}`;
      process.stdout.write(`[${runId}] ${stage} ${line}\n`);
      writeStageLog(stage, line);
      emit({
        type: "warning",
        stage,
        at: nowIso(),
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    error(msg, meta) {
      const line = `error ${msg}${fmtMeta(meta)}`;
      process.stderr.write(`[${runId}] ${stage} ${line}\n`);
      writeStageLog(stage, line);
      emit({
        type: "error",
        stage,
        at: nowIso(),
        message: msg,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    metric(name, value, meta) {
      const line = `metric ${name}=${String(value)}${fmtMeta(meta)}`;
      process.stdout.write(`[${runId}] ${stage} ${line}\n`);
      writeStageLog(stage, line);
      emit({
        type: "metric",
        stage,
        at: nowIso(),
        name,
        value,
        meta: meta ? (meta as Record<string, unknown>) : undefined,
      });
    },
    event(name, fields) {
      const line = `event ${name}${fmtMeta(fields)}`;
      process.stdout.write(`[${runId}] ${stage} ${line}\n`);
      writeStageLog(stage, line);
    },
  });

  const onDispose = (fn: DisposeFn): void => {
    disposers.push(fn);
  };

  const finalise = async (): Promise<void> => {
    // LIFO so resources registered later (browsers, file handles) tear down first.
    while (disposers.length > 0) {
      const fn = disposers.pop();
      if (!fn) continue;
      try {
        await fn();
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        process.stderr.write(
          `[${runId}] dispose error: ${msg}\n`,
        );
      }
    }
    // Close per-stage logs.
    for (const { logFile } of stageStreams.values()) {
      await new Promise<void>((res) => logFile.end(() => res()));
    }
    stageStreams.clear();
    await eventStream?.close();
  };

  return {
    runId,
    outDir,
    logger: rootLogger,
    startedAt: Date.now(),
    emit,
    forStage,
    onDispose,
    finalise,
  };
}
