/**
 * Shared global flag definitions for every `parity` subcommand.
 *
 * W5B.1 item 1 per docs/V2.0/observations/w5b1-cli-extensions.md.
 *
 * Citty does not have a true "global flag" concept; each command owns its own
 * args. This helper builds the same args fragment once and decorates every
 * subcommand definition so the flags appear consistently in `--help`, parse
 * identically, and can be read out of `args` by a single parser.
 *
 * Goal: every subcommand respects:
 *   --quiet            suppress non essential stdout
 *   --verbose          emit full debug
 *   --json             emit JSON instead of human format
 *   --no-color         disable ANSI colors
 *   --run-id <id>      override the generated run id
 *   --config <path>    load an alternate config file
 *
 * The helper is purely additive. Subcommands that do not yet honour a given
 * flag still accept it on the command line without error; downstream features
 * (Logger, RunContext, JSON output writer) consume the flags as they wire up.
 */

import type { ArgsDef, CommandDef } from "citty";

export interface GlobalFlagValues {
  quiet: boolean;
  verbose: boolean;
  json: boolean;
  noColor: boolean;
  runId?: string;
  config?: string;
}

/**
 * The args fragment that every parity subcommand merges into its own arg
 * map. Keep flag descriptions free of em dashes and double hyphens per the
 * project writing style rule.
 */
export const GLOBAL_FLAG_ARGS = {
  quiet: {
    type: "boolean",
    description: "Suppress non essential stdout. Errors still print.",
    default: false,
  },
  verbose: {
    type: "boolean",
    description: "Emit full debug output. Implies disabling quiet.",
    default: false,
  },
  json: {
    type: "boolean",
    description: "Emit JSON output instead of human readable text.",
    default: false,
  },
  "no-color": {
    type: "boolean",
    description: "Disable ANSI color sequences in human output.",
    default: false,
  },
  "run-id": {
    type: "string",
    description: "Override the autogenerated run id for this invocation.",
    valueHint: "id",
  },
  config: {
    type: "string",
    description: "Load configuration from an alternate path.",
    valueHint: "path",
  },
} as const;

/**
 * Wrap a citty command definition so its `args` includes every global flag.
 * Existing command args win on key collision so subcommands that already
 * defined a `--config` for some reason are not overwritten silently.
 *
 * The wrapper preserves the `meta`, `run`, `setup`, `cleanup`, `subCommands`,
 * and any other CommandDef fields untouched. Subcommands declared via the
 * `subCommands` map are NOT automatically wrapped; the caller wraps each
 * leaf command explicitly so the help output remains predictable.
 *
 * The return type is widened to `CommandDef<ArgsDef>` so the caller can
 * pass the wrapped value straight into `defineCommand` without TypeScript
 * complaining about the extra keys merged into the args map.
 */
export function withGlobalFlags(
  cmd: CommandDef<any>,
): CommandDef<ArgsDef> {
  const cmdArgs =
    ((cmd as { args?: Record<string, unknown> }).args as Record<
      string,
      unknown
    >) ?? {};
  const merged = { ...GLOBAL_FLAG_ARGS, ...cmdArgs };
  return { ...cmd, args: merged } as CommandDef<ArgsDef>;
}

/**
 * Read the global flag values out of a parsed citty args object. Accepts the
 * raw `args` from `run({ args })` so subcommand handlers can pluck out the
 * shared values without duplicating the casting boilerplate.
 */
export function readGlobalFlags(args: Record<string, unknown>): GlobalFlagValues {
  const quiet = args.quiet === true;
  const verbose = args.verbose === true;
  const json = args.json === true;
  const noColor = args["no-color"] === true;
  const runId =
    typeof args["run-id"] === "string" && args["run-id"].length > 0
      ? (args["run-id"] as string)
      : undefined;
  const config =
    typeof args.config === "string" && (args.config as string).length > 0
      ? (args.config as string)
      : undefined;
  return { quiet, verbose, json, noColor, runId, config };
}

/**
 * Apply the global flag side effects that are process wide:
 *   --no-color   sets NO_COLOR=1 in the environment so downstream libs honour it
 *   --verbose    sets DEBUG=1 so legacy log calls can branch on it
 *
 * Quiet, JSON, and run-id are consumed by the Logger and RunContext directly;
 * they have no env side effect.
 */
export function applyGlobalFlagEnv(flags: GlobalFlagValues): void {
  if (flags.noColor) {
    process.env.NO_COLOR = "1";
  }
  if (flags.verbose) {
    process.env.DEBUG = process.env.DEBUG ?? "1";
  }
}
