/**
 * SUMMARY.md generator.
 *
 * Phase 5 implementation per docs/V2.0/04-cli-and-logging-design.md (Part D, D.3)
 * and docs/V2.0/05-action-plan.md §4 Phase 5 task 5.
 *
 * Reads `.runs/<runId>/manifest.json` plus optional event scan from
 * `.runs/<runId>/pipeline.jsonl` and renders a human readable digest. The
 * file is the durable artefact Cameron keeps after deleting heavy clone
 * output, so it must stand alone.
 *
 * The template body avoids hyphens used as punctuation and em dashes per
 * the writing style rule. Hyphens inside flag names and code samples are
 * exempt.
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { readManifest, type RunManifest } from "./run-manifest.js";

function formatDuration(startedAt: string, endedAt?: string): string {
  if (!endedAt) return "in progress";
  const start = Date.parse(startedAt);
  const end = Date.parse(endedAt);
  if (Number.isNaN(start) || Number.isNaN(end)) return "unknown";
  const ms = end - start;
  if (ms < 1000) return `${ms}ms`;
  const seconds = ms / 1000;
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const mins = Math.floor(seconds / 60);
  const rem = Math.round(seconds - mins * 60);
  return `${mins}m ${rem}s`;
}

function formatStageDuration(stage: RunManifest["stages"][number]): string {
  if (!stage.endedAt) return "pending";
  return formatDuration(stage.startedAt, stage.endedAt);
}

function statusLabel(status: string): string {
  return status.toUpperCase();
}

function renderStageRow(stage: RunManifest["stages"][number]): string {
  const status = statusLabel(stage.status ?? "pending");
  const duration = formatStageDuration(stage);
  const metricSummary = stage.metrics
    ? Object.entries(stage.metrics)
        .map(([k, v]) => `${k}=${String(v)}`)
        .join(", ")
    : "";
  return `| ${stage.name} | ${status} | ${duration} | ${metricSummary} |`;
}

function renderIssuesSection(manifest: RunManifest): string {
  const lines: string[] = [];
  for (const stage of manifest.stages) {
    if (stage.warnings) {
      for (const w of stage.warnings) {
        lines.push(`- WARN [${stage.name}] ${w}`);
      }
    }
    if (stage.errors) {
      for (const e of stage.errors) {
        lines.push(`- FAIL [${stage.name}] ${e}`);
      }
    }
  }
  if (lines.length === 0) return "_No warnings or errors._";
  return lines.join("\n");
}

function renderParitySection(manifest: RunManifest): string {
  if (!manifest.parity) {
    return "_Parity verification did not run for this command._";
  }
  const { score, threshold, mode } = manifest.parity;
  const verdict =
    score >= threshold ? "pass (meets threshold)" : "fail (below threshold)";
  const scorePct = (score * 100).toFixed(2);
  const thresholdPct = (threshold * 100).toFixed(2);
  return [
    `- Score: ${scorePct}%`,
    `- Threshold: ${thresholdPct}%`,
    `- Comparison mode: ${mode}`,
    `- Verdict: ${verdict}`,
  ].join("\n");
}

function renderArtefactsSection(manifest: RunManifest): string {
  const entries = Object.entries(manifest.artefacts);
  if (entries.length === 0) return "_No artefacts recorded._";
  return entries.map(([name, path]) => `- ${name}: \`${path}\``).join("\n");
}

export function renderSummaryMarkdown(manifest: RunManifest): string {
  const duration = formatDuration(manifest.startedAt, manifest.endedAt);
  const target = manifest.target ?? "n/a";
  const url = manifest.url ?? "n/a";

  return `# Dr Parity Run Summary

**Run ID:** ${manifest.runId}
**Command:** \`${manifest.command}\`
**Target:** ${target}  **URL:** ${url}
**Started:** ${manifest.startedAt}  **Ended:** ${manifest.endedAt ?? "in progress"}  **Status:** ${manifest.status.toUpperCase()}
**Duration:** ${duration}

## Parity Outcome

${renderParitySection(manifest)}

## Stage Summary

| Stage | Status | Duration | Metrics |
|-------|--------|----------|---------|
${manifest.stages.map(renderStageRow).join("\n")}

## Issues Encountered

${renderIssuesSection(manifest)}

## Dr Parity Bugs / Gaps Spotted

<!-- USER-START: bugs -->
_Cameron edits below. Preserved across re-runs._
<!-- USER-END: bugs -->

## Suggested Improvements

<!-- USER-START: improvements -->
_Cameron edits below. Preserved across re-runs._
<!-- USER-END: improvements -->

## Cleanup Status

- Clone output: ${manifest.artefacts.cloneDir ?? "n/a"} (move out of repo when done)
- This SUMMARY.md is the durable record. Safe to delete the clone tree.

## Artefacts

${renderArtefactsSection(manifest)}

## Environment

- Node: ${manifest.env.node}
- Platform: ${manifest.env.platform}
- Git: ${manifest.env.gitSha}

_Generated by Dr Parity. Schema version ${manifest.schemaVersion}._
`;
}

export interface WriteSummaryOptions {
  /** Override the path the SUMMARY.md is written to. */
  outPath?: string;
}

/**
 * Read the manifest from `runDir`, render the markdown, write it to disk.
 * Preserves any existing `<!-- USER-START -->` / `<!-- USER-END -->` blocks.
 */
export async function writeSummary(
  runDir: string,
  options: WriteSummaryOptions = {},
): Promise<string> {
  const manifest = await readManifest({ runDir });
  const rendered = renderSummaryMarkdown(manifest);
  const merged = await mergeUserBlocks(
    rendered,
    options.outPath ?? join(runDir, "SUMMARY.md"),
  );
  const outPath = options.outPath ?? join(runDir, "SUMMARY.md");
  await fs.writeFile(outPath, merged, "utf8");
  return outPath;
}

/**
 * Match a USER block. Group 1 = block name, group 2 = inner body. The name
 * is matched in the END marker too via a back reference written as `\1`
 * (avoiding named capture so we stay compatible with the project's TS lib
 * target).
 */
const USER_BLOCK_RE =
  /<!-- USER-START: ([^>]+?) -->([\s\S]*?)<!-- USER-END: \1 -->/g;

async function mergeUserBlocks(
  rendered: string,
  existingPath: string,
): Promise<string> {
  let existing: string;
  try {
    existing = await fs.readFile(existingPath, "utf8");
  } catch {
    return rendered;
  }
  const preserved = new Map<string, string>();
  for (const match of existing.matchAll(USER_BLOCK_RE)) {
    const name = match[1];
    const body = match[2];
    if (!name) continue;
    preserved.set(name.trim(), body ?? "");
  }
  if (preserved.size === 0) return rendered;
  return rendered.replace(USER_BLOCK_RE, (full, name: string) => {
    const key = name.trim();
    const body = preserved.get(key);
    if (body === undefined) return full;
    return `<!-- USER-START: ${key} -->${body}<!-- USER-END: ${key} -->`;
  });
}
