/**
 * Compose the final `src/mocks/handlers.ts` file content. Owns the import
 * graph (fixture JSON imports), the optional `stableStringify` helper for
 * branching handlers, and the exported `handlers` array.
 */

import type { EndpointGroup } from './types';
import type { FixtureRef } from './build-fixtures';
import { buildBranchingHandler } from './branch-by-body';

export type HandlerBuildInput = {
  group: EndpointGroup;
  refs: FixtureRef[];
};

function fixtureImportPath(relativePath: string): string {
  // relativePath is e.g. "src/fixtures/get-api-posts-0.json".
  // From src/mocks/handlers.ts the relative path is "../fixtures/...".
  const m = /^src\/fixtures\/(.+)$/.exec(relativePath);
  if (!m) return `./${relativePath}`;
  return `../fixtures/${m[1]}`;
}

function dedupeImports(
  pairs: { importName: string; relativePath: string }[],
): { importName: string; relativePath: string }[] {
  const seen = new Set<string>();
  const out: { importName: string; relativePath: string }[] = [];
  for (const p of pairs) {
    if (seen.has(p.importName)) continue;
    seen.add(p.importName);
    out.push(p);
  }
  return out;
}

const STABLE_STRINGIFY_HELPER = [
  'function stableStringify(value: unknown): string {',
  '  if (value === null || typeof value !== "object") return JSON.stringify(value);',
  '  if (Array.isArray(value)) return "[" + value.map(stableStringify).join(",") + "]";',
  '  const obj = value as Record<string, unknown>;',
  '  const keys = Object.keys(obj).sort();',
  '  return "{" + keys.map((k) => JSON.stringify(k) + ":" + stableStringify(obj[k])).join(",") + "}";',
  '}',
].join('\n');

export function buildHandlersFile(inputs: HandlerBuildInput[]): string {
  const imports: { importName: string; relativePath: string }[] = [];
  const handlerSnippets: string[] = [];
  let needsStableStringify = false;

  for (const { group, refs } of inputs) {
    const { handlerCode, imports: importNames } = buildBranchingHandler(group, refs);
    handlerSnippets.push(handlerCode);

    // Wire imports back to their fixture file paths.
    for (const importName of importNames) {
      const ref = refs.find((r) => r.importName === importName);
      if (!ref) continue;
      imports.push({ importName, relativePath: ref.relativePath });
    }

    if (handlerCode.includes('stableStringify(')) needsStableStringify = true;
  }

  const uniqueImports = dedupeImports(imports);

  const header = [
    '/**',
    ' * Auto-generated by dr-parity Phase 4 (emit-mocks). Do not edit by hand:',
    ' * re-run the build to regenerate from the captured network log.',
    ' */',
    '',
    "import { http, HttpResponse } from 'msw';",
    "import type { HttpHandler } from 'msw';",
  ];

  const importLines = uniqueImports.map(
    (i) => `import ${i.importName} from '${fixtureImportPath(i.relativePath)}';`,
  );

  const body: string[] = [];
  if (needsStableStringify) {
    body.push('');
    body.push(STABLE_STRINGIFY_HELPER);
  }
  body.push('');
  body.push('export const handlers: HttpHandler[] = [');
  for (const snippet of handlerSnippets) body.push(snippet);
  body.push('];');
  body.push('');

  return [...header, ...importLines, ...body].join('\n');
}

export function buildEmptyHandlersFile(): string {
  return [
    '/**',
    ' * Auto-generated by dr-parity Phase 4 (emit-mocks). No XHR/fetch',
    ' * traffic was captured during the crawl, so the worker passes every',
    ' * request through to the network.',
    ' */',
    '',
    "import type { HttpHandler } from 'msw';",
    '',
    'export const handlers: HttpHandler[] = [];',
    '',
  ].join('\n');
}
