// Emit Zod schemas, TS types, SQLite DDL and a mapping note for the core
// projection entities, cross-checked against shapes inferred from the real
// captured export.

import { CORE_ENTITIES, type ColumnDef, type EntityDef } from "./entities.js";
import { inferShape, isStringEnum, enumValues, type ShapeModel } from "./infer.js";

export interface GeneratedArtifacts {
  zod: string;
  types: string;
  ddl: string;
  mapping: string;
}

/** Per-entity inferred shapes, used to annotate observed coverage. */
export type InferredShapes = Record<string, ShapeModel>;

export function inferFromSamples(samples: Record<string, unknown[]>): InferredShapes {
  const out: InferredShapes = {};
  for (const [entity, rows] of Object.entries(samples)) {
    out[entity] = inferShape(rows);
  }
  return out;
}

const HEADER = "// AUTO-GENERATED by `npm run schema:infer`. Do not edit by hand.\n";

function zodLeaf(col: ColumnDef): string {
  if (col.enum && col.enum.length) {
    const lits = col.enum.map((v) => JSON.stringify(v)).join(", ");
    return `z.enum([${lits}])`;
  }
  switch (col.zod) {
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "json":
      return "jsonValue";
  }
}

function zodColumn(col: ColumnDef): string {
  let expr = zodLeaf(col);
  if (col.nullable) expr += ".nullable()";
  return `  ${col.name}: ${expr},`;
}

function tsLeaf(col: ColumnDef): string {
  if (col.enum && col.enum.length) {
    return col.enum.map((v) => JSON.stringify(v)).join(" | ");
  }
  switch (col.zod) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "JsonValue";
  }
}

function tsColumn(col: ColumnDef): string {
  const t = tsLeaf(col);
  return `  ${col.name}: ${col.nullable ? `${t} | null` : t};`;
}

interface SqlColumnLine {
  /** Column definition without trailing comma. */
  def: string;
  /** FK comment appended after the comma, or empty. */
  comment: string;
}

function sqlColumn(col: ColumnDef): SqlColumnLine {
  const parts = [col.name, col.sql];
  if (col.primaryKey || !col.nullable) parts.push("NOT NULL");
  return {
    def: `  ${parts.join(" ")}`,
    comment: col.fkNote ? `  -- FK -> ${col.fkNote}` : "",
  };
}

function buildZod(entities: EntityDef[]): string {
  const blocks = entities.map((e) => {
    const cols = e.columns.map(zodColumn).join("\n");
    return [
      `export const ${e.name}Schema = z.object({`,
      cols,
      `});`,
      `export type ${e.name} = z.infer<typeof ${e.name}Schema>;`,
    ].join("\n");
  });
  return [
    HEADER,
    `import { z } from "zod";`,
    "",
    `// Recursive JSON value for embedded blobs (assignees, type_config, etc).`,
    `export type JsonValue =`,
    `  | string`,
    `  | number`,
    `  | boolean`,
    `  | null`,
    `  | JsonValue[]`,
    `  | { [key: string]: JsonValue };`,
    `export const jsonValue: z.ZodType<JsonValue> = z.lazy(() =>`,
    `  z.union([`,
    `    z.string(),`,
    `    z.number(),`,
    `    z.boolean(),`,
    `    z.null(),`,
    `    z.array(jsonValue),`,
    `    z.record(z.string(), jsonValue),`,
    `  ]),`,
    `);`,
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n");
}

function buildTypes(entities: EntityDef[]): string {
  const blocks = entities.map((e) => {
    const cols = e.columns.map(tsColumn).join("\n");
    return [`export interface ${e.name} {`, cols, `}`].join("\n");
  });
  return [
    HEADER,
    `export type JsonValue =`,
    `  | string`,
    `  | number`,
    `  | boolean`,
    `  | null`,
    `  | JsonValue[]`,
    `  | { [key: string]: JsonValue };`,
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n");
}

function buildDdl(entities: EntityDef[]): string {
  const tables = entities.map((e) => {
    const cols = e.columns.map(sqlColumn);
    const pkCols = e.columns.filter((c) => c.primaryKey).map((c) => c.name);
    const entries: string[] = cols.map((c) => c.def + (c.comment ? `||${c.comment}` : ""));
    if (pkCols.length) entries.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    // Join with commas, then move each FK comment to after the comma.
    const body = entries
      .map((entry, idx) => {
        const last = idx === entries.length - 1;
        const [def, comment] = entry.split("||");
        return last ? `${def}${comment ?? ""}` : `${def},${comment ?? ""}`;
      })
      .join("\n");
    return [
      `-- ${e.name}  (source: ${e.sourceFile})`,
      `CREATE TABLE IF NOT EXISTS ${e.table} (`,
      body,
      `);`,
    ].join("\n");
  });
  return [
    "-- AUTO-GENERATED by `npm run schema:infer`. Do not edit by hand.",
    "-- Projection tables (rebuildable read models). Events remain source of truth.",
    "PRAGMA foreign_keys = ON;",
    "",
    tables.join("\n\n"),
    "",
  ].join("\n");
}

function buildMapping(entities: EntityDef[], shapes: InferredShapes): string {
  const rows = entities.map((e) => {
    const shape = shapes[e.name];
    const observed = shape ? shape.fields.size : 0;
    const samples = shape ? shape.sampleCount : 0;
    const eps = e.endpoints.map((p) => `\`${p}\``).join("<br>");
    return `| ${e.name} | \`${e.table}\` | \`${e.sourceFile}\` | ${samples} | ${observed} | ${eps} |`;
  });

  const inferredDetail = entities
    .map((e) => {
      const shape = shapes[e.name];
      if (!shape || shape.fields.size === 0) return "";
      const fields = [...shape.fields.values()]
        .slice(0, 40)
        .map((f) => {
          const kinds = [...f.kinds].join("|") || "unknown";
          const flags = [
            f.isArray ? "array" : "",
            f.nullable ? "nullable" : "",
            f.optional ? "optional" : "",
            f.nested ? "nested" : "",
            isStringEnum(f) ? `enum(${enumValues(f).join(",")})` : "",
          ]
            .filter(Boolean)
            .join(" ");
          return `  - \`${f.name}\`: ${kinds}${flags ? ` [${flags}]` : ""}`;
        })
        .join("\n");
      return `### ${e.name} (${shape.sampleCount} samples)\n${fields}`;
    })
    .filter(Boolean)
    .join("\n\n");

  return [
    "# Entity → Source → Endpoint mapping",
    "",
    "Auto-generated by `npm run schema:infer`. Cross-references each core entity to",
    "its source export file and the internal endpoint(s) that return it",
    "(from `BACKEND_CONTRACT.json`). `samples`/`observed` reflect the real captured data.",
    "",
    "| Entity | Table | Source file | samples | observed fields | Internal endpoint(s) |",
    "|--------|-------|-------------|---------|-----------------|----------------------|",
    rows.join("\n"),
    "",
    "## Inferred field shapes (from real export)",
    "",
    inferredDetail,
    "",
  ].join("\n");
}

export function generateAll(shapes: InferredShapes): GeneratedArtifacts {
  return {
    zod: buildZod(CORE_ENTITIES),
    types: buildTypes(CORE_ENTITIES),
    ddl: buildDdl(CORE_ENTITIES),
    mapping: buildMapping(CORE_ENTITIES, shapes),
  };
}
