/**
 * README, .gitignore, .env.example, and the custom-elements JSX widening
 * shim. These are static enough that splitting each into its own file
 * would be ceremony.
 */

import { join } from 'node:path';

import { writeText, writeTextIfMissing } from './fs-utils';

export function writeReadme(outDir: string, name: string): void {
  const lines = [
    `# ${name}`,
    '',
    'Generated by the dr-parity `webapp` target. This is a React + Vite + MSW',
    'single-page application scaffold. The captured site has been split into',
    'route components under `src/pages/`, with captured assets mirrored into',
    '`public/`.',
    '',
    '## First run',
    '',
    '```bash',
    'npm install',
    'npm run msw:init   # copies mockServiceWorker.js into public/',
    'npm run dev',
    'npm run build',
    '```',
    '',
    '## Where things live',
    '',
    '- `index.html` is the SPA shell.',
    '- `src/main.tsx` boots React, starts MSW in dev, mounts `<BrowserRouter>`.',
    '- `src/App.tsx` defines the route table.',
    '- `src/pages/*.tsx` are the per-route page components.',
    '- `src/mocks/handlers.ts` holds MSW request handlers (filled by Phase 4).',
    '- `src/mocks/browser.ts` wires the handlers into the service worker.',
    '- `src/lib/` holds runtime helpers (e.g. post-hydration-sync).',
    '- `public/` holds every captured asset (CSS, JS, images, fonts).',
    '',
    '## Mocking',
    '',
    'MSW only runs in development (`import.meta.env.DEV`). Production builds',
    'ship without the worker so real network traffic flows through.',
    '',
  ];
  writeText(join(outDir, 'README.md'), lines.join('\n'));
}

export function writeEnvExample(outDir: string): void {
  const content = [
    '# Public, build-time env vars only. NO secrets in this file.',
    '# All VITE_* vars are exposed to the browser bundle.',
    '',
    'VITE_SITE_URL=https://example.com',
    '',
  ].join('\n');
  writeText(join(outDir, '.env.example'), content);
}

export function writeGitignore(outDir: string): void {
  const content = [
    'node_modules',
    'dist',
    'dist-ssr',
    '*.local',
    '.env',
    '.env.local',
    '.DS_Store',
    'public/mockServiceWorker.js',
    '',
  ].join('\n');
  writeTextIfMissing(join(outDir, '.gitignore'), content);
}

export function writeCustomElementsDts(outDir: string): void {
  const content = [
    '/**',
    ' * Allow any custom element / web component to pass typecheck.',
    ' * Captured sites may include tags like <a-link> or <swiper-slider>.',
    ' */',
    "import 'react';",
    '',
    'declare global {',
    '  namespace JSX {',
    '    interface IntrinsicElements {',
    '      [tag: string]: any;',
    '    }',
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
  writeText(join(outDir, 'src', 'jsx-custom-elements.d.ts'), content);
}
